@startuml
title Kilda Persistence, Service and Transport Layers

package "kilda-model" {
    class Flow
    class Switch
}

package "kilda-persistence-api" {
    interface PersistenceManager
    interface TransactionManager
    interface RepositoryFactory
    interface FlowRepository
    interface SwitchRepository

    PersistenceManager ..> TransactionManager : create
    PersistenceManager ..> RepositoryFactory : create

    RepositoryFactory ..> FlowRepository : create
    RepositoryFactory ..> SwitchRepository : create

    FlowRepository ..> Flow
    SwitchRepository ..> Switch
}

package "Service Layer" {
    class xyzService

    xyzService ..> Switch
    xyzService ..> TransactionManager
    xyzService ..> SwitchRepository
}

package "Transport Layer" {
    class xyzBolt
    class dtoToModelConverters
    class SwitchDto

    xyzBolt o-> "PersistenceManager" : locate & keep the instance
    xyzBolt o-> xyzService : create
    xyzBolt ..> dtoToModelConverters
    xyzBolt ..> SwitchDto
    dtoToModelConverters ..> Switch
    dtoToModelConverters ..> SwitchDto
}
@enduml