@startuml
title hub and spoke wfm mk7 error in worker
hide footbox

participant NB
participant "Kafka" as bus

box "Hub" #LightBlue
    participant "Spout" as sp_hub
    participant "Bolt" as bolt_hub
end box

participant "Coordinator\nBolt" as coordinator
box "Worker" #LightGreen
    participant "Spout" as sp_work
    collections "Bolt" as bolt_work
end box


NB ->> bus : request
sp_hub <<- bus
sp_hub ->> bolt_hub
bolt_hub ->> coordinator : register callback request
bolt_hub -> bolt_hub : prepare async jobs

== Hub to Worker communications ==
bolt_hub ->> bolt_work : emit tuple for async process

== Async Operations ==
bolt_work ->> coordinator : register callback request
bolt_work ->>x bus: error without error response
== Handle error ==
... worker operation timeout ...
coordinator ->> bolt_work : callback

alt retry
    loop
        sp_work ->> bolt_work: emit tuple for async process
    end
else cleanup if retry failed
    bolt_work -> bolt_work : cleanup
    bolt_work ->> coordinator : cancel callback
    bolt_work ->> bolt_hub: error response
    bolt_hub -> bolt_hub : cleanup
    bolt_hub ->> coordinator : cancel callback
    bolt_hub ->> bus: error response
    bus ->> NB: error response
end

@enduml