---
- hosts: localhost

  tasks:

  - name: create opt dir
    file: path=/opt state=directory

  - name: get kafka
    unarchive:
      src=/src/kafka_2.12-0.10.2.1.tgz
      dest=/opt
      remote_src=yes
      owner=root
      group=root

  - name: create kafka link
    file: src=/opt/kafka_2.12-0.10.2.1 dest=/opt/kafka state=link owner=root group=root

