TASK := functionalTest
STABLE_TAG := "stable"

build-base: {{if not (exists "/no_grpc_stub")}}build-grpc-stub {{end}}build-lock-keeper update-props docker/storm/lib
	docker build -t kilda/base-ubuntu:latest docker/base/kilda-base-ubuntu/
	docker build -t kilda/zookeeper:latest docker/zookeeper
	docker build -t kilda/kafka:latest docker/kafka
	docker build -t kilda/hbase:latest docker/hbase
	docker build -t kilda/storm:latest docker/storm
{{if not (exists "/no_opentsdb")}}	docker build -t kilda/opentsdb:latest docker/opentsdb
{{end}}{{if not (exists "/no_logstash")}}	docker build -t kilda/logstash:latest docker/logstash
{{end}}{{if not (exists "/no_elasticsearch")}}	docker build -t kilda/elasticsearch:latest docker/elasticsearch
{{end}}	$(MAKE) -C src-python/lab-service find-python-requirements
	docker build -t kilda/base-lab-service:latest docker/base/kilda-base-lab-service/

build-lock-keeper:
	cp src-python/lock-keeper/* docker/lock-keeper/
	docker build -t kilda/lock-keeper:latest docker/lock-keeper/

.PHONY: build-lock-keeper

.PHONY: build-grpc-stub
build-grpc-stub:
	cp src-python/grpc-stub/* docker/grpc-stub/
	docker build -t kilda/grpc-stub:latest docker/grpc-stub/

docker/storm/lib:
	docker/base/hacks/storm.requirements.download.sh

build-latest: build-base compile-green
	docker-compose build

build-stable: build-base compile-blue
	TAG=$(STABLE_TAG) docker-compose build

run-dev:
	docker-compose up

up-test-mode:
	@echo ~~
	@echo ~~ Starting KILDA, and will print the status of Storm Topology deployments
	@echo ~~ Once the topology deployments are done, it should be safe to test
	@echo ~~
	@echo
	cp -n .env.example .env
	TAG=$(STABLE_TAG) docker-compose up -d --scale northbound-blue-green=0 {{if not (exists "/no_grpc_speaker")}}--scale grpc-speaker-blue-green=0{{end}}
	docker-compose logs -f wfm
	$(MAKE) -C tools/elk-dashboards

up-stable:
	cp -n .env.example .env
	TAG=$(STABLE_TAG) WFM_TOPOLOGIES_MODE=blue docker-compose up -d --scale northbound-blue-green=0 {{if not (exists "/no_grpc_speaker")}}--scale grpc-speaker-blue-green=0{{end}}
	docker-compose logs -f wfm
	$(MAKE) -C tools/elk-dashboards

up-green:
	cp -n .env.example .env
	WFM_TOPOLOGIES_MODE=green docker-compose up -d floodlight_2 northbound-blue-green wfm {{if not (exists "/no_grpc_speaker")}}grpc-speaker-blue-green{{end}}
	docker-compose logs -f wfm
	$(MAKE) -C tools/elk-dashboards

up-blue:
	cp -n .env.example .env
	TAG=$(STABLE_TAG) WFM_TOPOLOGIES_MODE=blue docker-compose up -d floodlight_1 wfm
	docker-compose logs -f wfm
	$(MAKE) -C tools/elk-dashboards

up-log-mode: up-test-mode
	docker-compose logs -f

# keeping run-test for backwards compatibility (documentation) .. should deprecate
run-test: up-log-mode

.PHONY: clean-docker-files
clean-docker-files:
	if [ -d docker/BUILD ]; then rm -rf docker/BUILD; fi
	if [ -f docker/base/kilda-base-lab-service/merged-requirements.txt ]; then rm docker/base/kilda-base-lab-service/merged-requirements.txt; fi
	if [ -f docker/base-lab-service/log.json ]; then rm docker/base-lab-service/log.json; fi

.PHONY: clean-sources
clean-sources:
{{if not (exists "/no_gui")}}	$(MAKE) -C src-gui clean clean-java
{{end}}	$(MAKE) -C src-python/lab-service/lab clean
	cd src-java && ./gradlew clean

compile compile-blue: update-props-blue compile-common
	cd src-java && ./gradlew buildAndCopyArtifacts -PdestPath=../docker/BUILD --info --stacktrace $(GRADLE_COMPILE_PARAMS)

compile-green: update-props-green compile-common
	cd src-java && ./gradlew buildAndCopyArtifacts -PdestPath=../docker/BUILD --info --stacktrace $(GRADLE_COMPILE_PARAMS)

compile-common:
	$(MAKE) -C src-python/lab-service/lab test
	$(MAKE) -C src-python/lab-service/lab deploy-wheel
	$(MAKE) -C src-python/lab-service/traffexam deploy-wheel
{{if not (exists "/no_gui")}}	$(MAKE) -C src-gui build{{end}}

.PHONY: unit
unit: update-props
	cd src-java && ./gradlew test --stacktrace

.PHONY: checkstyle
checkstyle: update-props
	cd src-java && ./gradlew checkstyleMain checkstyleTest

.PHONY: sonar
sonar: update-props
	cd src-java && ./gradlew check jacocoTestReport sonarqube --stacktrace

.PHONY: clean-test
clean-test:
	docker-compose down
	docker-compose rm -fv
	docker volume list -q | grep kilda | xargs -r docker volume  rm

.PHONY: clean
clean: clean-sources clean-test clean-docker-files

FUNC_TESTS = src-java/testing/functional-tests

$(FUNC_TESTS)/kilda.properties:
	cp $(FUNC_TESTS)/kilda.properties.example $(FUNC_TESTS)/kilda.properties

$(FUNC_TESTS)/topology.yaml:
	cp $(FUNC_TESTS)/src/test/resources/topology.yaml $(FUNC_TESTS)/topology.yaml

copy-test-props: $(FUNC_TESTS)/kilda.properties $(FUNC_TESTS)/topology.yaml

.PHONY: run-func-tests func-tests test-topology
run-func-tests:
	cd src-java && ./gradlew :functional-tests:$(TASK) $(PARAMS)

# EXAMPLES:
#   make func-tests  // run all functional tests
#   make func-tests PARAMS='--tests org.openkilda.functionaltests.spec.links.*'  // run all tests from 'spec.links' package
#   make func-tests PARAMS='--tests LinkSpec'  // run all tests from 'LinkSpec' class
#   make func-tests PARAMS='--tests LinkSpec."Unable to delete an active link"'  // run a certain test from 'LinkSpec' class
# test-topology creates a virtual topology ready for testing, ensures that it is properly discovered
test-topology: TASK=runTest
test-topology: PARAMS=--tests HealthCheckSpecification
func-tests test-topology: copy-test-props run-func-tests
