@startuml
title Flow validation

actor User
boundary Northbound
participant FlowValidationHubBolt << Hub >>
participant SpeakerWorkerBolt <<Worker>>
participant Floodlight
participant FlowValidationService
database DAO

User -> Northbound : Flow validate

activate Northbound
Northbound -> FlowValidationHubBolt : FlowValidationRequest
activate FlowValidationHubBolt
FlowValidationHubBolt -> FlowValidationService : Get switches by flow id
activate FlowValidationService
FlowValidationService -> DAO : Get switches by flow id
activate DAO
DAO -> FlowValidationService : switches
deactivate DAO
FlowValidationService -> FlowValidationHubBolt : switches
deactivate FlowValidationService
loop switch in switches
  FlowValidationHubBolt -> SpeakerWorkerBolt : switch id
deactivate FlowValidationHubBolt
end
SpeakerWorkerBolt -> Floodlight : DumpRulesForNbworkerRequest
Floodlight -> SpeakerWorkerBolt : SwitchFlowEntries
SpeakerWorkerBolt -> FlowValidationHubBolt : SwitchFlowEntries
activate FlowValidationHubBolt
FlowValidationHubBolt -> FlowValidationHubBolt : Collect SwitchFlowEntries
FlowValidationHubBolt -> FlowValidationService : Validate flow
activate FlowValidationService
FlowValidationService -> DAO : Get flow by flow id
activate DAO
DAO -> FlowValidationService : flow
deactivate DAO
FlowValidationService -> DAO : Get flow segments by flow id and cookie
activate DAO
DAO -> FlowValidationService : flow segments
deactivate DAO
FlowValidationService -> FlowValidationService : Validate flow
FlowValidationService -> FlowValidationHubBolt : FlowValidationResponse
deactivate FlowValidationService
FlowValidationHubBolt -> Northbound : FlowValidationResponse
deactivate FlowValidationHubBolt
Northbound -> User : FlowValidationResponse
deactivate Northbound

@enduml