#!/bin/bash


echo
echo -•-•-•-•-•-•-•-•-•-•-•-•-•-•-•-•-•-
echo Verifying the commit with:
echo     make unit
echo -•-•-•-•-•-•-•-•-•-•-•-•-•-•-•-•-•-
echo

time make unit
RESULT=${?}

echo
echo -•-•-•-•-•-•-•-•-•-•-•-•-•-•-•-•-•-
echo Done .. RESULT = ${RESULT}
echo -•-•-•-•-•-•-•-•-•-•-•-•-•-•-•-•-•-
echo
echo

exit ${RESULT}