export const MessageObj = {
    unauthorised:"You are not authorised to access this page.",
    apply_changes:"Applying changes..",
    link_storage_config:"Checking link store configuration..",
    delete_contract:"Contract deleted successfully.",
    load_contract:"Loading contracts..",
    flow_detail:"Loading flow detail",
    load_ports:"Loading ports",
    loading_flows:"Loading flows",
    fetching_flows:"Fetching flows",
    re_routing:"Re-routing",
    re_routing_flows:"Re-routing flows",
    ping_flows:"Ping flows",
    no_ports:"No Ports available",
    no_flow_available:"No Flows available",
    flow_updated:"Updating flow",
    flow_updated_controller:"Flow updated successfully on controller",
    reloading_status_and_flow_path:"Reloading status and flow path after re-route..",
    flow_created:"Flow created successfully",
    flow_not_created:"Unable to create flow",
    flow_deleted:"Flow deleted successfully",
    otp_not_detected:"Unable to detect OTP",
    delete_flow_not_authorised:"You are not authorised to delete the flow.",
    loading_flow_path:"Loading flow path...",
    copied_to_clipboard:"Copied to clicboard",
    loading_isl:"Loading ISL detail",
    no_cost_data_returned:"API did not return Cost data.",
    no_isl:"No ISL Found",
    no_isl_available:"No ISL available",
    loading_isl_flows:"Loading ISL flows",
    no_isl_flows:"No ISL flows available",
    applying_changes:"Applying changes..",
    maintenance_mode_changed:"Maintenance mode changed successfully.",
    error_im_maintenance_mode:"Error in changing maintenance mode!",
    updating_bfd:"updating BFD flag..",
    bfd_flag_updated:"BFD flag updated successfully!",
    flows_evacuated:"All flows are evacuated successfully!",
    error_flows_evacuated:"Error in evacuating flows!",
    reverse_graph_no_data:"Backward graph API did not return data.",
    forward_graph_no_data:"Forward graph API did not return data.",
    updating_isl_bandwidth:"Updating ISL max bandwidth",
    isl_bandwidth_updated:"ISL bandwidth updated successfully!",
    isl_bandwidth_update_error:"Error in updating ISL bandwidth!",
    updating_isl_cost:"Updating ISL cost",
    isl_cost_updated:"ISL cost updated successfully!",
    error_isl_cost_updated:"Error in updating ISL cost!",
    deleting_isl:"Deleting ISL",
    isl_deleted:"ISL deleted successfully!",
    error_isl_delete:"Error in Isl deletion!",
    delete_isl_not_authorised:"You are not authorised to delete the ISL.",
    flow_rerouted:"Flow Re-routes successfully",
    flow_on_best_route:"Flow already on best route",
    loading_switches:"Loading switches..",
    no_switch_data:"No switch data",
    no_switch_found:"No Switch Found",
    fetching_network_paths:"fetching network paths...",
    no_data_found:"No data found",
    loading_is_detail:"Loading identity server details",
    validating_is_server:"Validating identity server details",
    unable_to_validate_is_server:"Unable to validate indentity server",
    is_server_detail_saved:"Identity server details saved successfully",
    loading_link_store:"Loading link store details",
    loading_link_store_setting:"Loading link store settings",
    deleting_link_store_setting:"Deleting link store settings",
    link_store_setting_deleted:"Link store settings deleted successfully",
    saving_link_store_setting:"Saving link store settings",
    link_store_setting_saved:"Link store settings saved successfully",
    loading_app_setting:"Loading application setting",
    saving_session_setting:"Saving session setting",
    session_setting_saved:"Session setting saved",
    saving_switch_name_store_setting:"Saving switch name source setting",
    switch_name_store_setting_saved:"Switch name source saved",
    user_unlock_time_setting_saved:"User unlock time setting saved",
    saving_unlock_time_setting:"Saving user unlock time setting",
    saving_login_attempt_setting:"Saving login attempt setting",
    user_login_attempt_setting_saved:"User login attempt setting saved",
    loading_switch_store:"Loading switch store settings",
    saving_switch_store:"Saving switch store settings",
    saved_switch_store:"Switch store settings saved successfully",
    error_saving_switch_store:"Error in saving switch store",
    deleting_switch_store:"Deleting switch store settings",
    switch_store_setting_deleted:"Switch store settings deleted successfully",
    error_in_deleting_switch_store:"Error in deleting switch store setting",
    nothing_changed:"Nothing is changed",
    updating_port_details:"Updating port details",
    port_configured:"Port configured successfully!",
    updating_discovery_flag:"Updating discovery packets flag ...",
    discovery_packets_updated:"Discovery Packets mode updated successful",
    error_updating_discovery_packets:"Error in updating discovery packets mode!",
    graph_api_did_not_return:"Graph API did not return data.",
    deleting_switch:"Deleting switch",
    switch_deleted:"Switch deleted successfully",
    not_authorised_to_delete_switch:"You are not authorised to delete the switch.",
    saving_switchname:"Saving switch name..",
    loading_switch_detail:"Loading switch details",
    no_switch_available:"No switch available",
    import_setting_saved:"Setting saved successfully!",
    loading_topology:"Loading topology..",
    reloading_topology_with_new_data:"Re-loading topology with new switch or isl",
    loading_user_activity:"Loading user activities",
    no_user_activity:"No useractivity data",
    adding_permission:"Adding permission",
    permission_added:"Permission added successfully!",
    assigning_roles:"Assigning roles",
    role_assigned:"Role assigned successfully!",
    updating_permission:"Updating permission",
    permission_updated:"Permission updated successfully!",
    loading_permission:"Loading permissions",
    something_wrong:"Something went wrong",
    connection_refused:"Connection refused",
    permission_status_changed:"Permission status changed successfully!",
    permission_removed:"Permission removed successfully!",
    adding_role:"Adding role",
    role_added:"Role added successfully!",
    assigning_user:"Assigning user",
    role_updated:"Role updated successfully!",
    getting_role:"Getting role",
    updating_role:"Updating role",
    loading_roles:"Loading roles",
    role_removed:"Role removed successfully!",
    adding_user:"Adding user",
    user_added:"User added successfully!",
    loading_details:"Loading details",
    updating_user:"Updating user",
    user_updated:"User data updated successfully!",
    loading_users:"Loading users",
    deleting_user:"Deleting user",
    user_deleted:"User removed successfully!",
    updating_user_status:"Updating user status",
    user_status_updated:"User status changed successfully!",
    unblok_user:"Unblocking user",
    user_unblocked:"User account is unblocked successfully",
    resetting_password:"Resetting Password",
    reset_pwd_mail_sent:"Reset password email sent successfully!",
    resetting_pwd_by_admin:"Resetting password by admin",
    pwd_reset:"Password Reset successfully!",
    resetting_twofa:"Resetting 2FA",
    twofa_reset:"User 2FA reset successfully!",
    changing_pwd:"Changing password..",
    pwd_changed:"Password changed successfully!",
    pwd_copied:"Password copied",
    session_expired:"Your session has been expired",
    loading_data:'Loading data..',
    error_loading_data:'Error loading data.',
    adding_provider:'Adding provider..',
    updating_provider:'Updating provider..',
    provider_added_success:'Provider added successfully.',
    provider_updated_success:'Provider updated successfully.',
    deleting_provider:"Deleting provider",
    provider_deleted_success:"Provider deleted successfully",
    switch_updated_success:"Switch location updated successfully.",
    switch_updated_error:"Error in updating switch location.",
    delete_bfd_properties:"Deleting BFD properties.",
    updating_bfd_properties:'Updating BFD properties values.',
    updating_bfd_properties_success:'BFD Properties updated successfully.',
    updating_bfd_properties_error:"Error in updating BFD properties.",
    BFD_properties_deleted:"BFD properties deleted successfully.",
    error_BFD_properties_delete:"Error in deleting BFD properties.",
    delete_isl_bfd_not_authorised:"You are not authorised to delete the ISL BFD Properties."

}