export const MessageObj = {
    unauthorised:"You are not authorised to access this page.",
    apply_changes:"Applying Changes..",
    link_storage_config:"Checking Link Store Configuration..",
    delete_contract:"Contract deleted successfully.",
    load_contract:"Loading Contracts..",
    flow_detail:"Loading Flow Detail",
    load_ports:"Loading Ports",
    loading_flows:"Loading Flows",
    fetching_flows:"Fetching flows",
    re_routing:"Re-routing",
    re_routing_flows:"Re-routing Flows",
    no_ports:"No Ports available",
    no_flow_available:"No Flows Available",
    flow_updated:"Updating flow",
    flow_updated_controller:"Flow updated successfully on controller",
    reloading_status_and_flow_path:"Reloading status and flow path after re-route..",
    flow_created:"Flow created successfully",
    flow_not_created:"Unable to create flow",
    flow_deleted:"Flow deleted successfully",
    otp_not_detected:"Unable to detect OTP",
    delete_flow_not_authorised:"You are not authorised to delete the flow.",
    loading_flow_path:"Loading Flow Path...",
    copied_to_clipboard:"Copied to clicboard",
    loading_isl:"Loading ISL detail",
    no_cost_data_returned:"API did not return Cost data.",
    no_isl:"No ISL Found",
    no_isl_available:"No ISL Available",
    loading_isl_flows:"Loading ISL Flows",
    no_isl_flows:"No ISL Flows Available",
    applying_changes:"Applying Changes..",
    maintenance_mode_changed:"Maintenance mode changed successfully.",
    error_im_maintenance_mode:"Error in changing maintenance mode!",
    updating_bfd:"updating BFD flag..",
    bfd_flag_updated:"BFD flag updated successfully!",
    flows_evacuated:"All flows are evacuated successfully!",
    error_flows_evacuated:"Error in evacuating flows!",
    reverse_graph_no_data:"Backward Graph API did not return data.",
    forward_graph_no_data:"Forward Graph API did not return data.",
    updating_isl_bandwidth:"Updating ISL max bandwidth",
    isl_bandwidth_updated:"ISL Bandwidth updated successfully!",
    isl_bandwidth_update_error:"Error in updating ISL Bandwidth!",
    updating_isl_cost:"Updating ISL cost",
    isl_cost_updated:"ISL cost updated successfully!",
    error_isl_cost_updated:"Error in updating ISL cost!",
    deleting_isl:"Deleting ISL",
    isl_deleted:"ISL deleted successfully!",
    error_isl_delete:"Error in Isl Deletion!",
    delete_isl_not_authorised:"You are not authorised to delete the ISL.",
    flow_rerouted:"Flow Re-routes Successfully",
    flow_on_best_route:"Flow Already On Best Route",
    loading_switches:"Loading Switches..",
    no_switch_data:"No switch data",
    no_switch_found:"No Switch Found",
    fetching_network_paths:"fetching network paths...",
    no_data_found:"No data found",
    loading_is_detail:"Loading Identity Server Details",
    validating_is_server:"Validating Identity Server Details",
    unable_to_validate_is_server:"Unable to validate indentity server",
    is_server_detail_saved:"Identity Server Details Saved Successfully",
    loading_link_store:"Loading Link Store Details",
    loading_link_store_setting:"Loading Link Store Settings",
    deleting_link_store_setting:"Deleting Link Store Settings",
    link_store_setting_deleted:"Link Store Settings Deleted Successfully",
    saving_link_store_setting:"Saving Link Store Settings",
    link_store_setting_saved:"Link Store Settings Saved Successfully",
    loading_app_setting:"Loading Application Setting",
    saving_session_setting:"Saving Session Setting",
    session_setting_saved:"Session Setting saved",
    saving_switch_name_store_setting:"Saving Switch Name Source Setting",
    switch_name_store_setting_saved:"Switch Name Source Saved",
    loading_switch_store:"Loading Switch Store Settings",
    saving_switch_store:"Saving Switch Store Settings",
    saved_switch_store:"Switch Store Settings Saved Successfully",
    error_saving_switch_store:"Error in saving switch store",
    deleting_switch_store:"Deleting Switch Store Settings",
    switch_store_setting_deleted:"Switch Store Settings Deleted Successfully",
    error_in_deleting_switch_store:"Error in deleting switch store setting",
    nothing_changed:"Nothing is changed",
    updating_port_details:"Updating Port Details",
    port_configured:"Port configured successfully!",
    updating_discovery_flag:"Updating Discovery Packets Flag ...",
    discovery_packets_updated:"Discovery Packets mode updated successful",
    error_updating_discovery_packets:"Error in updating discovery packets mode!",
    graph_api_did_not_return:"Graph API did not return data.",
    deleting_switch:"Deleting Switch",
    switch_deleted:"Switch deleted successfully",
    not_authorised_to_delete_switch:"You are not authorised to delete the switch.",
    saving_switchname:"Saving Switch Name..",
    loading_switch_detail:"Loading Switch Details",
    no_switch_available:"No Switch Available",
    import_setting_saved:"Setting saved successfully!",
    loading_topology:"Loading Topology..",
    reloading_topology_with_new_data:"Re-loading topology with new switch or isl",
    loading_user_activity:"Loading User Activities",
    no_user_activity:"No useractivity data",
    adding_permission:"Adding Permission",
    permission_added:"Permission added successfully!",
    assigning_roles:"Assigning Roles",
    role_assigned:"Role assigned successfully!",
    updating_permission:"Updating Permission",
    permission_updated:"Permission updated successfully!",
    loading_permission:"Loading Permissions",
    something_wrong:"Something went wrong",
    connection_refused:"Connection Refused",
    permission_status_changed:"Permission status changed successfully!",
    permission_removed:"Permission removed successfully!",
    adding_role:"Adding Role",
    role_added:"Role added successfully!",
    assigning_user:"Assigning User",
    role_updated:"Role updated successfully!",
    getting_role:"Getting Role",
    updating_role:"Updating Role",
    loading_roles:"Loading Roles",
    role_removed:"Role removed successfully!",
    adding_user:"Adding User",
    user_added:"User added successfully!",
    loading_details:"Loading Details",
    updating_user:"Updating User",
    user_updated:"User data updated successfully!",
    loading_users:"Loading Users",
    deleting_user:"Deleting User",
    user_deleted:"User removed successfully!",
    updating_user_status:"Updating User Status",
    user_status_updated:"User status changed successfully!",
    resetting_password:"Resetting Password",
    reset_pwd_mail_sent:"Reset Password email sent successfully!",
    resetting_pwd_by_admin:"Resetting Password By Admin",
    pwd_reset:"Password Reset successfully!",
    resetting_twofa:"Resetting 2FA",
    twofa_reset:"User 2FA reset successfully!",
    changing_pwd:"Changing password..",
    pwd_changed:"Password changed successfully!",
    pwd_copied:"Password Copied",
    session_expired:"Your session has been expired",
    loading_data:'Loading Data..',
    error_loading_data:'Error Loading Data.',
    adding_provider:'Adding Provider..',
    updating_provider:'Updating Provider..',
    provider_added_success:'Provider added Successfully.',
    provider_updated_success:'Provider updated Successfully.',
    deleting_provider:"Deleting provider",
    provider_deleted_success:"Provider deleted successfully",

}