// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: statistics.proto

package org.openkilda.server42.stats.messaging.flowrtt;

public final class Statistics {
  private Statistics() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FlowLatencyPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string flow_id = 1;</code>
     */
    java.lang.String getFlowId();
    /**
     * <code>string flow_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getFlowIdBytes();

    /**
     * <code>bool direction = 2;</code>
     */
    boolean getDirection();

    /**
     * <code>int64 t0 = 3;</code>
     */
    long getT0();

    /**
     * <code>int64 t1 = 4;</code>
     */
    long getT1();

    /**
     * <code>uint64 packet_id = 5;</code>
     */
    long getPacketId();
  }
  /**
   * Protobuf type {@code org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket}
   */
  public  static final class FlowLatencyPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket)
      FlowLatencyPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FlowLatencyPacket.newBuilder() to construct.
    private FlowLatencyPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FlowLatencyPacket() {
      flowId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FlowLatencyPacket();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FlowLatencyPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              flowId_ = s;
              break;
            }
            case 16: {

              direction_ = input.readBool();
              break;
            }
            case 24: {

              t0_ = input.readInt64();
              break;
            }
            case 32: {

              t1_ = input.readInt64();
              break;
            }
            case 40: {

              packetId_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.openkilda.server42.stats.messaging.flowrtt.Statistics.internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.openkilda.server42.stats.messaging.flowrtt.Statistics.internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.class, org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.Builder.class);
    }

    public static final int FLOW_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object flowId_;
    /**
     * <code>string flow_id = 1;</code>
     */
    public java.lang.String getFlowId() {
      java.lang.Object ref = flowId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        flowId_ = s;
        return s;
      }
    }
    /**
     * <code>string flow_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFlowIdBytes() {
      java.lang.Object ref = flowId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flowId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECTION_FIELD_NUMBER = 2;
    private boolean direction_;
    /**
     * <code>bool direction = 2;</code>
     */
    public boolean getDirection() {
      return direction_;
    }

    public static final int T0_FIELD_NUMBER = 3;
    private long t0_;
    /**
     * <code>int64 t0 = 3;</code>
     */
    public long getT0() {
      return t0_;
    }

    public static final int T1_FIELD_NUMBER = 4;
    private long t1_;
    /**
     * <code>int64 t1 = 4;</code>
     */
    public long getT1() {
      return t1_;
    }

    public static final int PACKET_ID_FIELD_NUMBER = 5;
    private long packetId_;
    /**
     * <code>uint64 packet_id = 5;</code>
     */
    public long getPacketId() {
      return packetId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFlowIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, flowId_);
      }
      if (direction_ != false) {
        output.writeBool(2, direction_);
      }
      if (t0_ != 0L) {
        output.writeInt64(3, t0_);
      }
      if (t1_ != 0L) {
        output.writeInt64(4, t1_);
      }
      if (packetId_ != 0L) {
        output.writeUInt64(5, packetId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFlowIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, flowId_);
      }
      if (direction_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, direction_);
      }
      if (t0_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, t0_);
      }
      if (t1_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, t1_);
      }
      if (packetId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, packetId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket)) {
        return super.equals(obj);
      }
      org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket other = (org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket) obj;

      if (!getFlowId()
          .equals(other.getFlowId())) return false;
      if (getDirection()
          != other.getDirection()) return false;
      if (getT0()
          != other.getT0()) return false;
      if (getT1()
          != other.getT1()) return false;
      if (getPacketId()
          != other.getPacketId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FLOW_ID_FIELD_NUMBER;
      hash = (53 * hash) + getFlowId().hashCode();
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDirection());
      hash = (37 * hash) + T0_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getT0());
      hash = (37 * hash) + T1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getT1());
      hash = (37 * hash) + PACKET_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPacketId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket)
        org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.openkilda.server42.stats.messaging.flowrtt.Statistics.internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.openkilda.server42.stats.messaging.flowrtt.Statistics.internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.class, org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.Builder.class);
      }

      // Construct using org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        flowId_ = "";

        direction_ = false;

        t0_ = 0L;

        t1_ = 0L;

        packetId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.openkilda.server42.stats.messaging.flowrtt.Statistics.internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacket_descriptor;
      }

      @java.lang.Override
      public org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket getDefaultInstanceForType() {
        return org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.getDefaultInstance();
      }

      @java.lang.Override
      public org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket build() {
        org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket buildPartial() {
        org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket result = new org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket(this);
        result.flowId_ = flowId_;
        result.direction_ = direction_;
        result.t0_ = t0_;
        result.t1_ = t1_;
        result.packetId_ = packetId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket) {
          return mergeFrom((org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket other) {
        if (other == org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.getDefaultInstance()) return this;
        if (!other.getFlowId().isEmpty()) {
          flowId_ = other.flowId_;
          onChanged();
        }
        if (other.getDirection() != false) {
          setDirection(other.getDirection());
        }
        if (other.getT0() != 0L) {
          setT0(other.getT0());
        }
        if (other.getT1() != 0L) {
          setT1(other.getT1());
        }
        if (other.getPacketId() != 0L) {
          setPacketId(other.getPacketId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object flowId_ = "";
      /**
       * <code>string flow_id = 1;</code>
       */
      public java.lang.String getFlowId() {
        java.lang.Object ref = flowId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          flowId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string flow_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFlowIdBytes() {
        java.lang.Object ref = flowId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          flowId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string flow_id = 1;</code>
       */
      public Builder setFlowId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        flowId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string flow_id = 1;</code>
       */
      public Builder clearFlowId() {
        
        flowId_ = getDefaultInstance().getFlowId();
        onChanged();
        return this;
      }
      /**
       * <code>string flow_id = 1;</code>
       */
      public Builder setFlowIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        flowId_ = value;
        onChanged();
        return this;
      }

      private boolean direction_ ;
      /**
       * <code>bool direction = 2;</code>
       */
      public boolean getDirection() {
        return direction_;
      }
      /**
       * <code>bool direction = 2;</code>
       */
      public Builder setDirection(boolean value) {
        
        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool direction = 2;</code>
       */
      public Builder clearDirection() {
        
        direction_ = false;
        onChanged();
        return this;
      }

      private long t0_ ;
      /**
       * <code>int64 t0 = 3;</code>
       */
      public long getT0() {
        return t0_;
      }
      /**
       * <code>int64 t0 = 3;</code>
       */
      public Builder setT0(long value) {
        
        t0_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 t0 = 3;</code>
       */
      public Builder clearT0() {
        
        t0_ = 0L;
        onChanged();
        return this;
      }

      private long t1_ ;
      /**
       * <code>int64 t1 = 4;</code>
       */
      public long getT1() {
        return t1_;
      }
      /**
       * <code>int64 t1 = 4;</code>
       */
      public Builder setT1(long value) {
        
        t1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 t1 = 4;</code>
       */
      public Builder clearT1() {
        
        t1_ = 0L;
        onChanged();
        return this;
      }

      private long packetId_ ;
      /**
       * <code>uint64 packet_id = 5;</code>
       */
      public long getPacketId() {
        return packetId_;
      }
      /**
       * <code>uint64 packet_id = 5;</code>
       */
      public Builder setPacketId(long value) {
        
        packetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 packet_id = 5;</code>
       */
      public Builder clearPacketId() {
        
        packetId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket)
    }

    // @@protoc_insertion_point(class_scope:org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket)
    private static final org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket();
    }

    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FlowLatencyPacket>
        PARSER = new com.google.protobuf.AbstractParser<FlowLatencyPacket>() {
      @java.lang.Override
      public FlowLatencyPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FlowLatencyPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FlowLatencyPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FlowLatencyPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FlowLatencyPacketBucketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacketBucket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
     */
    java.util.List<org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket> 
        getPacketList();
    /**
     * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
     */
    org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket getPacket(int index);
    /**
     * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
     */
    int getPacketCount();
    /**
     * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
     */
    java.util.List<? extends org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketOrBuilder> 
        getPacketOrBuilderList();
    /**
     * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
     */
    org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketOrBuilder getPacketOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacketBucket}
   */
  public  static final class FlowLatencyPacketBucket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacketBucket)
      FlowLatencyPacketBucketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FlowLatencyPacketBucket.newBuilder() to construct.
    private FlowLatencyPacketBucket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FlowLatencyPacketBucket() {
      packet_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FlowLatencyPacketBucket();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FlowLatencyPacketBucket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                packet_ = new java.util.ArrayList<org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket>();
                mutable_bitField0_ |= 0x00000001;
              }
              packet_.add(
                  input.readMessage(org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          packet_ = java.util.Collections.unmodifiableList(packet_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.openkilda.server42.stats.messaging.flowrtt.Statistics.internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacketBucket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.openkilda.server42.stats.messaging.flowrtt.Statistics.internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacketBucket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket.class, org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket.Builder.class);
    }

    public static final int PACKET_FIELD_NUMBER = 1;
    private java.util.List<org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket> packet_;
    /**
     * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
     */
    public java.util.List<org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket> getPacketList() {
      return packet_;
    }
    /**
     * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
     */
    public java.util.List<? extends org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketOrBuilder> 
        getPacketOrBuilderList() {
      return packet_;
    }
    /**
     * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
     */
    public int getPacketCount() {
      return packet_.size();
    }
    /**
     * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
     */
    public org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket getPacket(int index) {
      return packet_.get(index);
    }
    /**
     * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
     */
    public org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketOrBuilder getPacketOrBuilder(
        int index) {
      return packet_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < packet_.size(); i++) {
        output.writeMessage(1, packet_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < packet_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, packet_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket)) {
        return super.equals(obj);
      }
      org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket other = (org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket) obj;

      if (!getPacketList()
          .equals(other.getPacketList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPacketCount() > 0) {
        hash = (37 * hash) + PACKET_FIELD_NUMBER;
        hash = (53 * hash) + getPacketList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacketBucket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacketBucket)
        org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.openkilda.server42.stats.messaging.flowrtt.Statistics.internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacketBucket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.openkilda.server42.stats.messaging.flowrtt.Statistics.internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacketBucket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket.class, org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket.Builder.class);
      }

      // Construct using org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPacketFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (packetBuilder_ == null) {
          packet_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          packetBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.openkilda.server42.stats.messaging.flowrtt.Statistics.internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacketBucket_descriptor;
      }

      @java.lang.Override
      public org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket getDefaultInstanceForType() {
        return org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket.getDefaultInstance();
      }

      @java.lang.Override
      public org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket build() {
        org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket buildPartial() {
        org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket result = new org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket(this);
        int from_bitField0_ = bitField0_;
        if (packetBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            packet_ = java.util.Collections.unmodifiableList(packet_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.packet_ = packet_;
        } else {
          result.packet_ = packetBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket) {
          return mergeFrom((org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket other) {
        if (other == org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket.getDefaultInstance()) return this;
        if (packetBuilder_ == null) {
          if (!other.packet_.isEmpty()) {
            if (packet_.isEmpty()) {
              packet_ = other.packet_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePacketIsMutable();
              packet_.addAll(other.packet_);
            }
            onChanged();
          }
        } else {
          if (!other.packet_.isEmpty()) {
            if (packetBuilder_.isEmpty()) {
              packetBuilder_.dispose();
              packetBuilder_ = null;
              packet_ = other.packet_;
              bitField0_ = (bitField0_ & ~0x00000001);
              packetBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPacketFieldBuilder() : null;
            } else {
              packetBuilder_.addAllMessages(other.packet_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket> packet_ =
        java.util.Collections.emptyList();
      private void ensurePacketIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          packet_ = new java.util.ArrayList<org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket>(packet_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket, org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.Builder, org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketOrBuilder> packetBuilder_;

      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public java.util.List<org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket> getPacketList() {
        if (packetBuilder_ == null) {
          return java.util.Collections.unmodifiableList(packet_);
        } else {
          return packetBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public int getPacketCount() {
        if (packetBuilder_ == null) {
          return packet_.size();
        } else {
          return packetBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket getPacket(int index) {
        if (packetBuilder_ == null) {
          return packet_.get(index);
        } else {
          return packetBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public Builder setPacket(
          int index, org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket value) {
        if (packetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePacketIsMutable();
          packet_.set(index, value);
          onChanged();
        } else {
          packetBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public Builder setPacket(
          int index, org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.Builder builderForValue) {
        if (packetBuilder_ == null) {
          ensurePacketIsMutable();
          packet_.set(index, builderForValue.build());
          onChanged();
        } else {
          packetBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public Builder addPacket(org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket value) {
        if (packetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePacketIsMutable();
          packet_.add(value);
          onChanged();
        } else {
          packetBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public Builder addPacket(
          int index, org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket value) {
        if (packetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePacketIsMutable();
          packet_.add(index, value);
          onChanged();
        } else {
          packetBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public Builder addPacket(
          org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.Builder builderForValue) {
        if (packetBuilder_ == null) {
          ensurePacketIsMutable();
          packet_.add(builderForValue.build());
          onChanged();
        } else {
          packetBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public Builder addPacket(
          int index, org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.Builder builderForValue) {
        if (packetBuilder_ == null) {
          ensurePacketIsMutable();
          packet_.add(index, builderForValue.build());
          onChanged();
        } else {
          packetBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public Builder addAllPacket(
          java.lang.Iterable<? extends org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket> values) {
        if (packetBuilder_ == null) {
          ensurePacketIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, packet_);
          onChanged();
        } else {
          packetBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public Builder clearPacket() {
        if (packetBuilder_ == null) {
          packet_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          packetBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public Builder removePacket(int index) {
        if (packetBuilder_ == null) {
          ensurePacketIsMutable();
          packet_.remove(index);
          onChanged();
        } else {
          packetBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.Builder getPacketBuilder(
          int index) {
        return getPacketFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketOrBuilder getPacketOrBuilder(
          int index) {
        if (packetBuilder_ == null) {
          return packet_.get(index);  } else {
          return packetBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public java.util.List<? extends org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketOrBuilder> 
           getPacketOrBuilderList() {
        if (packetBuilder_ != null) {
          return packetBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(packet_);
        }
      }
      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.Builder addPacketBuilder() {
        return getPacketFieldBuilder().addBuilder(
            org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.getDefaultInstance());
      }
      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.Builder addPacketBuilder(
          int index) {
        return getPacketFieldBuilder().addBuilder(
            index, org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.getDefaultInstance());
      }
      /**
       * <code>repeated .org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacket packet = 1;</code>
       */
      public java.util.List<org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.Builder> 
           getPacketBuilderList() {
        return getPacketFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket, org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.Builder, org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketOrBuilder> 
          getPacketFieldBuilder() {
        if (packetBuilder_ == null) {
          packetBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket, org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacket.Builder, org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketOrBuilder>(
                  packet_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          packet_ = null;
        }
        return packetBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacketBucket)
    }

    // @@protoc_insertion_point(class_scope:org.openkilda.server42.stats.messaging.flowrtt.FlowLatencyPacketBucket)
    private static final org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket();
    }

    public static org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FlowLatencyPacketBucket>
        PARSER = new com.google.protobuf.AbstractParser<FlowLatencyPacketBucket>() {
      @java.lang.Override
      public FlowLatencyPacketBucket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FlowLatencyPacketBucket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FlowLatencyPacketBucket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FlowLatencyPacketBucket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.openkilda.server42.stats.messaging.flowrtt.Statistics.FlowLatencyPacketBucket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacketBucket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacketBucket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020statistics.proto\022.org.openkilda.server" +
      "42.stats.messaging.flowrtt\"b\n\021FlowLatenc" +
      "yPacket\022\017\n\007flow_id\030\001 \001(\t\022\021\n\tdirection\030\002 " +
      "\001(\010\022\n\n\002t0\030\003 \001(\003\022\n\n\002t1\030\004 \001(\003\022\021\n\tpacket_id" +
      "\030\005 \001(\004\"l\n\027FlowLatencyPacketBucket\022Q\n\006pac" +
      "ket\030\001 \003(\0132A.org.openkilda.server42.stats" +
      ".messaging.flowrtt.FlowLatencyPacketb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacket_descriptor,
        new java.lang.String[] { "FlowId", "Direction", "T0", "T1", "PacketId", });
    internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacketBucket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacketBucket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_openkilda_server42_stats_messaging_flowrtt_FlowLatencyPacketBucket_descriptor,
        new java.lang.String[] { "Packet", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
