@startuml
title Current implementation of ISL discovery


participant Floodlight as FL
participant Switch_A as SWA
participant Switch_B as SWB
control kilda.topo.disco as DI
participant EventTopology as EV
database DB
participant IslStatsTopology as ST
control kilda.otsdb as OTSDB
participant OpenTSDBTopology as OTOP


activate FL
FL -> FL : set current timestemp **T**
FL -> SWA : Discovery Packet
deactivate FL
activate SWA
SWA -> SWB : Discovery Packet
deactivate SWA
activate SWB
SWB -> FL : Discovery Packet
deactivate SWB
activate FL
FL -> FL : calculate latency \n**curTime - T - controller latency**
FL -> DI : IslInfoData
deactivate FL
DI -> EV : IslInfoData
activate EV
EV -> DB : Store ISL
deactivate EV

DI -> ST : IslInfoData
activate ST
ST -> OTSDB : latency metric
deactivate ST
OTSDB -> OTOP : latency metric

@enduml
