#!/bin/bash
export TSDB_VERSION="::TSDB_VERSION::"
echo "Sleeping for 30 seconds to give HBase time to warm up"
sleep 30

echo "checking tables in hbase"
/app/create_table.py

echo "starting opentsdb"
/opt/opentsdb/opentsdb-${TSDB_VERSION}/build/tsdb tsd --port=4242 --staticroot=/opt/opentsdb/opentsdb-${TSDB_VERSION}/build/staticroot --cachedir=/tmp --auto-metric
