@startuml
title FL alive tracking

participant MonotonicTime as Time
participant "FL-router" as fl_router

box "FL IO Kafka topics" #LightGreen
control "FLn-write" as fl_write.kafka
control "FLn-read" as fl_read.kafka
end box

participant FL

...

Time -> fl_router: tick
activate fl_router
note right of fl_router: activate outage alert
fl_router -> fl_read.kafka: AliveRequest
fl_read.kafka -> FL: AliveRequest
activate FL
FL -> fl_write.kafka: AliveResponse
deactivate FL
fl_write.kafka -> fl_router: AliveResponse
note right of fl_router: update last seen time
deactivate fl_router
...
Time -> fl_router: tick
activate fl_router
note right of fl_router: activate outage alert
fl_router -> fl_read.kafka: AliveRequest
fl_read.kafka ->X FL: AliveRequest

Time -> fl_router: tick
note right of fl_router: handle region outage
opt subset of switches become unavailable
<-- fl_router: emit UnmanagedSwitchNotification
...
<-- fl_router: emit UnmanagedSwitchNotification
end opt
deactivate fl_router

@enduml
