@startuml

title FL communication channel

box "Region-less topics" #LightGreen
control "topicA"
control "topicB"
end box

box "FL router" #LightBlue
control "c_spout" as rc_spout
participant "controller2speaker" as cs_proxy
participant "speaker2controller" as sc_proxy
control "s_spout" as rs_spout
end box

box "Region topics" #LightGreen
control "topicA-regionA" as region_topicA
control "topicB-regionA" as region_topicB
end box

collections FL

== Controller to speaker stream ==
-> topicA : json

topicA -> rc_spout : json
note right of rc_spout : decode json
rc_spout -> cs_proxy : message
activate cs_proxy

note right of cs_proxy : extract switchId
note right of cs_proxy : lookup switchId-to-region map

cs_proxy -> region_topicA
deactivate cs_proxy

region_topicA -> FL : json

== Speaker to controller stream ==

FL -> region_topicB : json
region_topicB -> rs_spout : json
note right of rs_spout : decode json

rs_spout -> sc_proxy : message
activate sc_proxy
note right of sc_proxy : extract switchId

sc_proxy -> cs_proxy : region update
note right of cs_proxy : update switchId-to-region map

sc_proxy -> topicB : json
deactivate sc_proxy

<- topicB : json

@enduml
