flow-update-fsm.png was created with draw.io to make the diagram easier to read.

The current file was created so that in the case of a FSM design change we have the textual difference of what was
changed. This file exactly describes all the transitions in the implemented FSM.

@startuml
title Flow Update FSM
hide empty description

[*] --> FLOW_VALIDATED : next
[*] --> FINISHED_WITH_ERROR : error

FLOW_VALIDATED --> FLOW_UPDATED : next
FLOW_VALIDATED --> REVERTING_FLOW_STATUS : timeout
FLOW_VALIDATED --> REVERTING_FLOW_STATUS : error

FLOW_UPDATED --> PRIMARY_RESOURCES_ALLOCATED : next
FLOW_UPDATED --> RESOURCE_ALLOCATION_COMPLETED : update-endpoint-rules-only
FLOW_UPDATED --> REVERTING_FLOW: timeout
FLOW_UPDATED --> REVERTING_FLOW: error

PRIMARY_RESOURCES_ALLOCATED --> PROTECTED_RESOURCES_ALLOCATED : next
PRIMARY_RESOURCES_ALLOCATED --> NEW_RULES_REVERTED : timeout
PRIMARY_RESOURCES_ALLOCATED --> NEW_RULES_REVERTED : error
PRIMARY_RESOURCES_ALLOCATED --> REVERTING_ALLOCATED_RESOURCES : no-path-found

PROTECTED_RESOURCES_ALLOCATED --> RESOURCE_ALLOCATION_COMPLETED : next
PROTECTED_RESOURCES_ALLOCATED --> NEW_RULES_REVERTED : timeout
PROTECTED_RESOURCES_ALLOCATED --> NEW_RULES_REVERTED : error
PROTECTED_RESOURCES_ALLOCATED --> REVERTING_ALLOCATED_RESOURCES : no-path-found

RESOURCE_ALLOCATION_COMPLETED --> INSTALLING_NON_INGRESS_RULES : next
RESOURCE_ALLOCATION_COMPLETED --> NEW_RULES_REVERTED : timeout
RESOURCE_ALLOCATION_COMPLETED --> NEW_RULES_REVERTED : error

INSTALLING_NON_INGRESS_RULES : response-received / remove pending command
INSTALLING_NON_INGRESS_RULES : error-received / put failed command
INSTALLING_NON_INGRESS_RULES --> NON_INGRESS_RULES_INSTALLED : rules-installed
INSTALLING_NON_INGRESS_RULES --> PATHS_SWAP_REVERTED : timeout
INSTALLING_NON_INGRESS_RULES --> PATHS_SWAP_REVERTED : error

NON_INGRESS_RULES_INSTALLED --> VALIDATING_NON_INGRESS_RULES : next
NON_INGRESS_RULES_INSTALLED --> PATHS_SWAP_REVERTED : timeout
NON_INGRESS_RULES_INSTALLED --> PATHS_SWAP_REVERTED : error

VALIDATING_NON_INGRESS_RULES : response-received / remove pending command
VALIDATING_NON_INGRESS_RULES : error-received / put failed command
VALIDATING_NON_INGRESS_RULES --> NON_INGRESS_RULES_VALIDATED : rules-validated
VALIDATING_NON_INGRESS_RULES --> PATHS_SWAP_REVERTED : timeout
VALIDATING_NON_INGRESS_RULES --> PATHS_SWAP_REVERTED : error
VALIDATING_NON_INGRESS_RULES --> PATHS_SWAP_REVERTED : missing-rule-found

NON_INGRESS_RULES_VALIDATED --> PATHS_SWAPPED : next
NON_INGRESS_RULES_VALIDATED --> REVERTING_PATHS_SWAP : timeout
NON_INGRESS_RULES_VALIDATED --> REVERTING_PATHS_SWAP : error

PATHS_SWAPPED --> INSTALLING_INGRESS_RULES : next
PATHS_SWAPPED --> REVERTING_PATHS_SWAP : timeout
PATHS_SWAPPED --> REVERTING_PATHS_SWAP : error

INSTALLING_INGRESS_RULES : response-received / remove pending command
INSTALLING_INGRESS_RULES : error-received / put failed command
INSTALLING_INGRESS_RULES --> INGRESS_RULES_INSTALLED : rules-installed
INSTALLING_INGRESS_RULES --> INGRESS_RULES_INSTALLED : ingress-is-skipped
INSTALLING_INGRESS_RULES --> REVERTING_PATHS_SWAP : timeout
INSTALLING_INGRESS_RULES --> REVERTING_PATHS_SWAP : error

INGRESS_RULES_INSTALLED --> VALIDATING_INGRESS_RULES : next
INGRESS_RULES_INSTALLED --> REVERTING_PATHS_SWAP : timeout
INGRESS_RULES_INSTALLED --> REVERTING_PATHS_SWAP : error

VALIDATING_INGRESS_RULES : response-received / remove pending command
VALIDATING_INGRESS_RULES : error-received / put failed command
VALIDATING_INGRESS_RULES --> INGRESS_RULES_VALIDATED : rules-validated
VALIDATING_INGRESS_RULES --> REVERTING_PATHS_SWAP : timeout
VALIDATING_INGRESS_RULES --> REVERTING_PATHS_SWAP : error
VALIDATING_INGRESS_RULES --> REVERTING_PATHS_SWAP : missing-rule-found

INGRESS_RULES_VALIDATED --> NEW_PATHS_INSTALLATION_COMPLETED : next
INGRESS_RULES_VALIDATED --> REVERTING_PATHS_SWAP : timeout
INGRESS_RULES_VALIDATED --> REVERTING_PATHS_SWAP : error

NEW_PATHS_INSTALLATION_COMPLETED --> REMOVING_OLD_RULES : next
NEW_PATHS_INSTALLATION_COMPLETED --> REVERTING_PATHS_SWAP : timeout
NEW_PATHS_INSTALLATION_COMPLETED --> REVERTING_PATHS_SWAP : error

REMOVING_OLD_RULES : response-received / remove pending command
REMOVING_OLD_RULES : error-received / put failed command
REMOVING_OLD_RULES --> OLD_RULES_REMOVED : rules-removed
REMOVING_OLD_RULES --> OLD_RULES_REMOVED : error

OLD_RULES_REMOVED --> OLD_PATHS_REMOVAL_COMPLETED : next
OLD_RULES_REMOVED --> UPDATING_FLOW_STATUS : update-endpoint-rules-only

OLD_PATHS_REMOVAL_COMPLETED --> DEALLOCATING_OLD_RESOURCES : next
OLD_PATHS_REMOVAL_COMPLETED --> DEALLOCATING_OLD_RESOURCES : error

DEALLOCATING_OLD_RESOURCES --> OLD_RESOURCES_DEALLOCATED : next

OLD_RESOURCES_DEALLOCATED --> UPDATING_FLOW_STATUS : next
OLD_RESOURCES_DEALLOCATED --> UPDATING_FLOW_STATUS : error

UPDATING_FLOW_STATUS --> FLOW_STATUS_UPDATED : next

FLOW_STATUS_UPDATED --> NOTIFY_FLOW_MONITOR : next
FLOW_STATUS_UPDATED --> NOTIFY_FLOW_MONITOR_WITH_ERROR : error

NOTIFY_FLOW_MONITOR --> FINISHED : next

NOTIFY_FLOW_MONITOR_WITH_ERROR --> FINISHED_WITH_ERROR : next
FINISHED_WITH_ERROR : enter / report error

FINISHED --> [*]
FINISHED_WITH_ERROR --> [*]

REVERTING_PATHS_SWAP : enter / report error
REVERTING_PATHS_SWAP --> PATHS_SWAP_REVERTED : next

PATHS_SWAP_REVERTED : enter / report error
PATHS_SWAP_REVERTED --> REVERTING_NEW_RULES : next
PATHS_SWAP_REVERTED --> REVERTING_NEW_RULES : error

REVERTING_NEW_RULES : response-received / remove pending command
REVERTING_NEW_RULES : error-received / put failed command
REVERTING_NEW_RULES --> NEW_RULES_REVERTED : rules-removed
REVERTING_NEW_RULES --> NEW_RULES_REVERTED : error

NEW_RULES_REVERTED --> REVERTING_ALLOCATED_RESOURCES : next
NEW_RULES_REVERTED --> REVERTING_ALLOCATED_RESOURCES : error
NEW_RULES_REVERTED --> REVERTING_FLOW : update-endpoint-rules-only

REVERTING_ALLOCATED_RESOURCES : enter / report error
REVERTING_ALLOCATED_RESOURCES --> RESOURCES_ALLOCATION_REVERTED : next
REVERTING_ALLOCATED_RESOURCES --> RESOURCES_ALLOCATION_REVERTED : error

RESOURCES_ALLOCATION_REVERTED --> REVERTING_FLOW : next
RESOURCES_ALLOCATION_REVERTED --> REVERTING_FLOW : error

REVERTING_FLOW : enter / report error
REVERTING_FLOW --> REVERTING_FLOW_STATUS : next
REVERTING_FLOW --> REVERTING_FLOW_STATUS : error

REVERTING_FLOW_STATUS --> NOTIFY_FLOW_MONITOR_WITH_ERROR : next
REVERTING_FLOW_STATUS --> NOTIFY_FLOW_MONITOR_WITH_ERROR : error

@enduml
