[template]

src = "server42/server42-control-storm-stub.application.properties.tmpl"
dest = "src-java/server42/server42-control-storm-stub/src/main/resources/application.properties"
keys = [ "/" ]
mode = "0644"
