package org.openkilda.simulator.classes;

public enum Commands {
    DO_DISCOVER_ISL_COMMAND,
    DO_DISCOVER_ISL_P2_COMMAND,
    DO_DISCOVER_PATH_COMMAND,
    DO_INSTALL_INGRESS_FLOW,
    DO_INSTALL_EGRESS_FLOW,
    DO_INSTALL_TRANSIT_FLOW,
    DO_INSTALL_ONESWITCH_FLOW,
    DO_DELETE_FLOW,
    DO_PORT_MOD,
    DO_SWITCH_MOD,
    DO_ADD_SWITCH,
    DO_REMOVE_SWITCH,
    DO_GET_FLOWS,
    DO_GET_PORT_STATS,
    DO_GET_PORT_STATUS,
    DO_GET_SWITCH_STATUS;
}
