@startuml
title Reroute flow with protected path

control kilda.topo.reroute
box "Reroute Topology" #LightBlue
    participant RerouteBolt
    participant FlowThrottlingBolt
    participant RerouteService
end box
database FlowRepository
control kilda.flow
box "Flow Topology" #LightGreen
    participant FlowService
    participant TransactionBolt
end box

kilda.topo.reroute ->> RerouteBolt: RerouteAffectedFlows
activate RerouteBolt
RerouteBolt -> RerouteService: processRerouteAffectedFlows
activate RerouteService

==Protected flow rerouting==
RerouteService -> FlowRepository: getActiveBackupedFlowsWithAffectedPrimaryPath
FlowRepository --> RerouteService: Set(FlowId, PathId)
loop foreach FlowId in AffectedPrimaryPathSet
    note right of RerouteService: reroute affected primary path
    RerouteService -> RerouteService: add (FlowId, PathId) to reroute list
    RerouteService -> kilda.flow: emit FlowSwapPath(FlowId, PathId)
end

group Swapping Flow Path
    kilda.flow ->> FlowService: FlowSwapPath
    activate FlowService
    FlowService -> FlowRepository: swap primary path
    FlowService ->> TransactionBolt: install new ingress\nand remove old ingress
    deactivate FlowService
end

RerouteService -> FlowRepository: getActiveBackupedFlowsWithAffectedProtectedPath
FlowRepository --> RerouteService: Set(FlowId, PathId)
loop foreach FlowId in AffectedProtectedPathSet
    note right of RerouteService: reroute protected path
    RerouteService -> RerouteService: add (FlowId, PathId) to reroute list
end

==Regular(without protected) flow rerouting==
RerouteService -> FlowRepository: getActiveAffectedRegularFlows
FlowRepository --> RerouteService: List(FlowId)
loop foreach in retrieved list
    RerouteService -> RerouteService: add (FlowId, None) to reroute list
end

==Emit reroute commands==
RerouteService --> RerouteBolt: List(FlowId, Optional<PathId>)
deactivate RerouteService

loop foreach (FlowId, Optional<PathId>) pair
    RerouteBolt ->> FlowThrottlingBolt: emit flow reroutes
    deactivate RerouteBolt
    activate FlowThrottlingBolt
end
FlowThrottlingBolt ->> kilda.flow: emit FlowRerouteRequests
deactivate FlowThrottlingBolt

==Path rerouting==
kilda.flow ->> FlowService: FlowRerouteRequest
activate FlowService
FlowService -> FlowService: Performs specified flow path rerouting
FlowService ->> TransactionBolt: install and remove rules
deactivate FlowService

@enduml
