INSERT INTO "VERSION" (Version_ID, Version_Number, Version_Deployment_Date)
VALUES (2, 2, CURRENT_TIMESTAMP);


INSERT  INTO "ACTIVITY_TYPE" (activity_type_id, activity_name) VALUES 
	(1, 'FLOW_VALIDATE'),
	(2, 'FLOW_REROUTE'),
	(3, 'SWITCH_RULES'),
	(4, 'ISL_UPDATE_COST');
	
INSERT INTO "KILDA_PERMISSION" (PERMISSION_ID, PERMISSION, IS_EDITABLE, IS_ADMIN_PERMISSION, STATUS_ID, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE,DESCRIPTION) VALUES 
	(32, 'menu_user_activity', false, false, 1, 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP, 'Permission for user activity menu');
	
INSERT INTO "ROLE_PERMISSION" (ROLE_ID,PERMISSION_ID) VALUES 
	(2, 32);
