@startuml
title PCE strategies

participant "PCE Client" as Client
participant PathComputerFactory
participant PathComputer
participant PathFinder
participant AvailableNetworkFactory
participant AvailableNetwork
database Neo4J

activate Client

Client -> PathComputerFactory: getPathComputer

activate PathComputerFactory
create PathComputer
PathComputerFactory -> PathComputer: create with config
create PathFinder
PathComputer -> PathFinder: create with config
PathFinder -> PathComputer
PathComputer --> PathComputerFactory
PathComputerFactory --> Client
deactivate PathComputerFactory

activate PathComputer
Client -> PathComputer: getPath
note right of Client: with path computation strategy param

PathComputer -> AvailableNetworkFactory: getAvailableNetwork with build strategy
activate AvailableNetworkFactory
AvailableNetworkFactory -> Neo4J: get active links
Neo4J --> AvailableNetworkFactory
create AvailableNetwork
AvailableNetworkFactory -> AvailableNetwork: create from retrieved links
AvailableNetwork --> AvailableNetworkFactory
AvailableNetworkFactory --> PathComputer: AvailableNetwork
deactivate AvailableNetworkFactory

PathComputer -> PathFinder: find path in network
activate PathFinder
note right of PathComputer: with weight function based on path computation strategy param
PathFinder -> PathComputer: best found path if any
deactivate PathFinder
PathComputer --> Client: computed pathPair
deactivate PathComputer

deactivate Client
@enduml
