databaseChangeLog:
  - preConditions:
      - onFail: HALT
      - onFailMessage: "Failed preconditions for migration '029-remove-multi-table-fields.yaml'.\n
        \n
        Before run this migration you must be sure that values of all following fields are 'true':\n
         1. switch_properties.multi_table\n
         2. flow_path.src_with_multi_table\n
         3. flow_path.dst_with_multi_table\n
         4. path_segment.src_with_multi_table\n
         5. path_segment.dst_with_multi_table\n
         6. flow_mirror_path.egress_with_multi_table\n"
      - sqlCheck:
          expectedResult: 0
          sql: "SELECT COUNT(*) FROM switch_properties WHERE multi_table <> true"
      - sqlCheck:
          expectedResult: 0
          sql: "SELECT COUNT(*) FROM flow_path WHERE src_with_multi_table <> true"
      - sqlCheck:
          expectedResult: 0
          sql: "SELECT COUNT(*) FROM flow_path WHERE dst_with_multi_table <> true"
      - sqlCheck:
          expectedResult: 0
          sql: "SELECT COUNT(*) FROM path_segment WHERE src_with_multi_table <> true"
      - sqlCheck:
          expectedResult: 0
          sql: "SELECT COUNT(*) FROM path_segment WHERE dst_with_multi_table <> true"
      - sqlCheck:
          expectedResult: 0
          sql: "SELECT COUNT(*) FROM flow_mirror_path WHERE egress_with_multi_table <> true"

  - changeSet:
      id: tag
      author: snikitin
      changes:
        - tagDatabase:
            tag: 029-remove-multi-table-fields
  - changeSet:
      id: remove_multi_table_fields_from_flow_path
      author: snikitin
      changes:
        - sql: "DROP PROPERTY flow_path.src_with_multi_table"
        - sql: "DROP PROPERTY flow_path.dst_with_multi_table"
      rollback:
        - sql: "CREATE PROPERTY flow_path.src_with_multi_table IF NOT EXISTS STRING"
        - sql: "CREATE PROPERTY flow_path.dst_with_multi_table IF NOT EXISTS STRING"
        - sql: "UPDATE flow_path SET src_with_multi_table = true"
        - sql: "UPDATE flow_path SET dst_with_multi_table = true"
  - changeSet:
      id: remove_multi_table_fields_from_path_segment
      author: snikitin
      changes:
        - sql: "DROP PROPERTY path_segment.src_with_multi_table"
        - sql: "DROP PROPERTY path_segment.dst_with_multi_table"
      rollback:
        - sql: "CREATE PROPERTY path_segment.src_with_multi_table IF NOT EXISTS STRING"
        - sql: "CREATE PROPERTY path_segment.dst_with_multi_table IF NOT EXISTS STRING"
        - sql: "UPDATE path_segment SET src_with_multi_table = true"
        - sql: "UPDATE path_segment SET dst_with_multi_table = true"
  - changeSet:
      id: remove_multi_table_fields_from_flow_mirror_path
      author: snikitin
      changes:
        - sql: "DROP PROPERTY flow_mirror_path.egress_with_multi_table"
      rollback:
        - sql: "CREATE PROPERTY flow_mirror_path.egress_with_multi_table IF NOT EXISTS STRING"
        - sql: "UPDATE flow_mirror_path SET egress_with_multi_table = true"
  - changeSet:
      id: remove_multi_table_fields_from_switch_properties
      author: snikitin
      changes:
        - sql: "DROP PROPERTY switch_properties.multi_table"
      rollback:
        - sql: "CREATE PROPERTY switch_properties.multi_table IF NOT EXISTS STRING"
        - sql: "UPDATE switch_properties SET multi_table = true"
  - changeSet:
      id: remove_multi_table_fields_from_kilda_configuration
      author: snikitin
      changes:
        - sql: "DROP PROPERTY kilda_configuration.use_multi_table"
      rollback:
        - sql: "CREATE PROPERTY kilda_configuration.use_multi_table IF NOT EXISTS STRING"
        - sql: "UPDATE kilda_configuration SET use_multi_table = true"
