@startuml
title Flow cache update

participant FlowHS
control topo.flowhs.flow.monitoring
participant Server42
control server42.stats.flowrtt
box flow-monitoring topology
participant FlowSpout
participant FlowLatencySpout
participant TickBolt
participant FlowCacheBolt
end box

==New path for flow==
FlowHS -> topo.flowhs.flow.monitoring : new path for flow
topo.flowhs.flow.monitoring -> FlowSpout : new path for flow
FlowSpout -> FlowCacheBolt : new path for flow
FlowCacheBolt -> FlowCacheBolt : update flow cache

==Flow stats==
Server42 -> server42.stats.flowrtt : FlowRttStatsData
server42.stats.flowrtt -> FlowLatencySpout : FlowRttStatsData
FlowLatencySpout -> FlowCacheBolt : FlowRttStatsData
FlowCacheBolt -> FlowCacheBolt : update flow cache

@enduml
