@startuml
title Flow-monitoring topology
hide empty description

[*] ---> FlowSpout
[*] ---> FlowLatencySpout
[*] ---> IslLatencySpout
[*] ---> IslSpout

FlowSpout ---> FlowCacheBolt : flow path changes
FlowLatencySpout ---> FlowCacheBolt : server42 stats
IslLatencySpout ---> IslCacheBolt : isl latency
IslSpout ---> SplitterBolt : isl changed info
SplitterBolt ---> IslCacheBolt : uni-isl changed info
TickBolt ---> FlowCacheBolt : tick
TickBolt ---> ActionBolt : tick
FlowCacheBolt ---> IslCacheBolt : get actual latency for isl
IslCacheBolt ---> FlowCacheBolt : actual latency for isl
FlowCacheBolt ---> ActionBolt : calculated flow latency
FlowCacheBolt ---> StatsBolt : calculated flow latency
ActionBolt ---> RerouteBolt : reroute request

@enduml
