@startuml

title Sample of Domain Model with DataMapper pattern

actor FL

box "Transport Layer" #Orange
	participant Kafka
	participant Storm
end box

box "Service Layer" #LightYellow
	participant SwitchService
end box

box "Domain Model Layer" #LightBlue
	participant Switch
end box

box "Database Layer" #LightGreen
	participant SwitchDataMapper
	participant DB
end box

== Create Switch ==

FL -> Kafka : switch added
Kafka -> Storm
Storm -> SwitchService
activate SwitchService
create Switch
SwitchService -> Switch : create Switch
SwitchService <- Switch


SwitchService -> SwitchDataMapper : save(Switch)
activate SwitchDataMapper
SwitchDataMapper -> DB : create entity in DB
SwitchDataMapper <- DB
SwitchService <- SwitchDataMapper
deactivate SwitchDataMapper
deactivate SwitchService


== Update Switch ==

FL -> Kafka : switch changed
Kafka -> Storm
Storm -> SwitchService
activate SwitchService

SwitchService -> SwitchDataMapper : getSwitchById
activate SwitchDataMapper
SwitchDataMapper -> DB : get entity from DB
SwitchDataMapper <- DB
SwitchDataMapper -> SwitchDataMapper: Map data from DB to Domain Object
SwitchService <- SwitchDataMapper : return Switch
deactivate SwitchDataMapper
SwitchService -> SwitchService : update Switch state

SwitchService -> SwitchDataMapper : save(Switch)
activate SwitchDataMapper
SwitchDataMapper -> DB : update entity in DB
SwitchDataMapper <- DB
SwitchService <- SwitchDataMapper
deactivate SwitchDataMapper
deactivate SwitchService


@enduml