@startuml
title Path Calculation with transaction resource allocation

participant FlowService
participant PathComputer
participant IslRepository
database NetworkDB
participant FlowRepository
database FlowDB
participant ResourcePoolService
database ResourceDB


==STEP: Path Calculation==
activate FlowService
group DB transaction
    FlowService -> PathComputer : path calculation
    activate PathComputer
    PathComputer -> PathComputer : find a path
    activate PathComputer
    PathComputer -> IslRepository : get available paths
    activate IslRepository
    IslRepository -> NetworkDB
    IslRepository <-- NetworkDB
    PathComputer <-- IslRepository
    deactivate IslRepository
    deactivate PathComputer
    alt Path has been found
        FlowService <-- PathComputer : the path
        deactivate PathComputer

        FlowService -> FlowRepository : build and store a flow path
        activate FlowRepository
        FlowRepository -> FlowDB
        deactivate FlowRepository
        FlowService -> IslRepository : alloc bandwidth
        activate IslRepository
        IslRepository -> NetworkDB
        deactivate IslRepository
    else Path not found
        FlowService <-- PathComputer : can't find path
    end
end

==STEP: Resource Allocation==

FlowService -> ResourcePoolService : alloc flow resources
activate ResourcePoolService
loop try to allocate resources X times in case of failure
    group DB transaction
        ResourcePoolService -> ResourceDB : alloc cookie
        ResourcePoolService -> ResourceDB : alloc meter
        ResourcePoolService -> ResourceDB : alloc transit_vlan
    end
end
FlowService <-- ResourcePoolService
deactivate ResourcePoolService
FlowService -> FlowRepository : update the flow path with the resources
activate FlowRepository
FlowRepository -> FlowDB
deactivate FlowRepository
deactivate FlowService
@enduml
