@startuml
title Hub And Spoke Flow Delete

actor User
boundary "NB v2" as NB
participant FlowDeleteHub << Hub >>
participant DAO
participant ResourcePool
participant CommandBuilder
database DAO
participant History
participant SpeakerWorker

User -> NB : Delete request

activate NB
NB -> FlowDeleteHub : Delete flow
activate FlowDeleteHub
FlowDeleteHub -> FlowDeleteHub : Start flow deletion workflow

FlowDeleteHub -> History : Flow deletion started
FlowDeleteHub -> DAO : Get flow from DB
FlowDeleteHub <- DAO : Requested flow
alt The flow exists and not in PROGRESS state
    NB <- FlowDeleteHub : The flow with details
    User <- NB : Flow deletion response
else The flow not found
    NB <- FlowDeleteHub : Requested flow doesn't exist
    User <- NB : Flow deletion error
end

FlowDeleteHub -> History : Flow validated

loop For each flow path
    FlowDeleteHub -> CommandBuilder : Get delete commands for path rules
    CommandBuilder -> CommandBuilder : Build commands: remove ingress \nand egress/transit rules
    FlowDeleteHub <- CommandBuilder: Rule deletion commands
end

loop For each in commands
    FlowDeleteHub -> SpeakerWorker : Send a delete command
end

deactivate FlowDeleteHub

loop For each response
    FlowDeleteHub <- SpeakerWorker : A command response
    activate FlowDeleteHub
    alt The rule is deleted successfully
        FlowDeleteHub -> FlowDeleteHub : Mark corresponding rule as removed
    else The rule is not deleted (timeout, error occurred)
        alt Retry attemps is not exhausted
            FlowDeleteHub -> SpeakerWorker : Retry a delete command
        else
            FlowDeleteHub -> History : Failed to delete the rule
        end
    end
    deactivate FlowDeleteHub
end

alt Received responses for all commands
    FlowDeleteHub -> FlowDeleteHub
    activate FlowDeleteHub
    FlowDeleteHub -> History : Rules removed

    FlowDeleteHub -> DAO : Remove flow path and segments
    FlowDeleteHub -> DAO : Update ISLs' available bw
    FlowDeleteHub -> ResourcePool : Deallocate resources
    ResourcePool -> DAO : Release used cookies, vlans
    FlowDeleteHub -> DAO : Remove flow

    FlowDeleteHub -> History : Flow deleted
    deactivate FlowDeleteHub
end

@enduml