@startuml
title Ability to exclude given graph from path computation

participant "PCE Client" as Client
participant "PathComputer" as Computer
participant "AvailableNetwork" as Network
database "Neo4J" as DB

activate Client

Client -> Computer: getAvailableNetwork()
activate Computer
Computer -> DB: get active links
DB --> Computer
create Network
Computer -> Network: create from retrieved links
Network --> Computer
Computer --> Client: AvailableNetwork
deactivate Computer

note right of Client: Has list of excluding ISL
Client -> Network: excludeIsls() or excludeSwitches()

Client -> Computer: getPathFromAvailableNetwork()
activate Computer
Computer -> Computer: findPathInNetwork()
Computer --> Client: computed FlowPair
deactivate Computer

deactivate Client
@enduml