
node {
    stage ("Pull") {
      checkout scm
    }

    stage ("Build") {
      sh 'docker run -it --rm -v m2:/root/.m2 -v $(PWD):/app -w /app kilda/builder-maven:latest mvn compile'
    }

    stage ("Test") {
      sh 'docker run -it --rm -v m2:/root/.m2 -v $(PWD):/app -w /app kilda/builder-maven:latest mvn verify'
    }

}
