@startuml
title Reroute all flows which go through a particular ISL

participant Client

participant Northbound

control kilda.northbound
control kilda.topo.nb

participant NbWorkerTopology

participant Neo4j

control kilda.flow

Client -> Northbound : PATCH /links/under-maintenance\nRequest body: LinkUnderMaintenanceDto

activate Northbound
Northbound -> kilda.topo.nb : CommandMessage\nUpdateLinkUnderMaintenanceRequest
kilda.topo.nb -> NbWorkerTopology : CommandMessage\nUpdateLinkUnderMaintenanceRequest
activate NbWorkerTopology

NbWorkerTopology -> Neo4j : Query to get link\ninformation
activate Neo4j
Neo4j -> NbWorkerTopology : Isl
deactivate Neo4j

alt

NbWorkerTopology -> NbWorkerTopology : Update cost
NbWorkerTopology -> Neo4j : Update isl
NbWorkerTopology -> kilda.northbound : InfoData\nIslInfoData
kilda.northbound -> Northbound : InfoData\nIslInfoData
Northbound -> Client : LinkDto

opt isl is "Under maintenance" and evacuate
NbWorkerTopology -> Neo4j : Query to get flows for\na particular link
activate Neo4j
Neo4j -> NbWorkerTopology : Flows
deactivate Neo4j
loop flows
    NbWorkerTopology -> kilda.flow : CommandMessage\nFlowRerouteRequest
end
end

else link does not exist

NbWorkerTopology -> kilda.northbound : ErrorMessage
deactivate NbWorkerTopology
kilda.northbound -> Northbound : ErrorMessage
Northbound -> Client : HTTP 404: Isl not found
deactivate Northbound
end

@enduml