package org.openkilda.functionaltests.model.cleanup

enum CleanupActionType {
    DELETE_FLOW,
    DELETE_YFLOW,
    DELETE_HAFLOW,
    RESTORE_ISL,
    PORT_UP,
    RESET_ISLS_COST,
    DELETE_ISLS_PROPERTIES,
    RESET_ISL_PARAMETERS,
    REVIVE_SWITCH,
    RESTORE_FEATURE_TOGGLE,
    RESTORE_KILDA_CONFIGURATION,
    SYNCHRONIZE_SWITCH,
    CLEAN_LINK_DELAY,
    RESTORE_SWITCH_PROPERTIES,
    RESET_SWITCH_MAINTENANCE,
    DELETE_LAG_LOGICAL_PORT,
    RESTORE_PORT_PROPERTIES,
    RESTORE_A_SWITCH_FLOWS,
    DELETE_MIRROR,
    OTHER
}