Internal data
* BFD-discriminator
* isUp (initial false)

Internal signals
* fail

Input signals
* port-up
* port-down
* enable (ISL-FSM)
* disable (ISL-FSM)
* FL-ok (worker)
* FL-fail (worker)
* FL-timeout (worker)

Output signals
* bfd-up
* bfd-down
* bfd-kill

@startuml
title BFD port FSM

[*] --> INIT

state initChoice <<choice>>
INIT --> initChoice : history / load persistence-data

initChoice --> IDLE : [BFD-discriminator is empty]
initChoice --> CLEANING : [BFD-discriminator is set]

IDLE --> INSTALLING : enable
IDLE -l-> FAIL : port-up

INSTALLING --> ACTIVE : port-up
INSTALLING --> CLEANING : FL-fail [match reuest-key] /\nreport error
INSTALLING --> CLEANING : disable
INSTALLING --> FAIL : fail
INSTALLING --> TERMINATE : kill
INSTALLING : enter / save remote SwitchId
INSTALLING : enter / allocate BFD-discriminator
INSTALLING : enter / emit BFD-session setup
INSTALLING : enter / save request-key

state failChoice <<choice>>
state cleaningChoice <<choice>>

CLEANING --> cleaningChoice : FL-ok / release BFD-discriminator
CLEANING --> failChoice : FL-fail [match request-key] /\nreport error
CLEANING --> HOUSEKEEPING : kill
CLEANING : enter / emit BFD-session remove
CLEANING : enter / save request-key
CLEANING : port-up / set isUp = true
CLEANING : port-down / set isUp = false

failChoice --> IDLE : [discrimator-not-found] / release BFD-discrimator
failChoice --> FAIL : [else]

cleaningChoice --> IDLE : [not isUp]
cleaningChoice --> WAIT_RELEASE : [isUp]

WAIT_RELEASE --> IDLE : port-down
WAIT_RELEASE : exit : set isUp = false

state ACTIVE {
    [*] --> UP

    UP --> DOWN : port-down
    UP : enter / emit bfd-up
    UP : enter / set isUp = true

    DOWN --> UP : port-up
    DOWN : enter / emit bfd-down
    DOWN : enter / set isUp = false
}
ACTIVE --> CLEANING : disable
ACTIVE --> TERMINATE : kill
ACTIVE : exit / emit bfd-kill

TERMINATE --> HOUSEKEEPING : next
TERMINATE : enter / emit BFD-session remove
TERMINATE : enter / save request-key

HOUSEKEEPING --> [*] : FL-ok / release BFD-discriminator\nFL-fail / report error

FAIL -r-> IDLE : port-down
FAIL : enable / report malfunction
FAIL : disable / report malfunction

@enduml
