@startuml

== Add Port Watch ==
PortHandler -> WatchListBolt: watch request switch_id+port\nrouting by switch_id
WatchListBolt -> WatchListBolt: add switch_id+port to watch list

== Del Port Watch ==
PortHandler -> WatchListBolt: del watch request switch_id+port\nrouting by switch_id
WatchListBolt -> WatchListBolt: remove switch_id+port from watch list
WatchListBolt -> WatcherBolt: remove switch_id+port
WatcherBolt -> WatcherBolt: remove from await list
WatcherBolt -> WatcherBolt: remove round-trip-status

== Enable/disable exhausted-poll-mode ==
note over UniIslHandler
	We emit enable exhausted-poll-mode only for ports without links
end note
UniIslHandler -> WatchListBolt: enable/disable exhausted-poll-mode\nfor switch_id+port
WatchListBolt -> WatchListBolt: set exhausted-poll-mode flag in true/false\nfor switch_id+port

== Enable/disable auxiliary-poll-mode ==
IslHandler -> WatchListBolt: enable/disable auxiliary-poll-mode\nfor switch_id+port
WatchListBolt -> WatchListBolt: set auxiliary-poll-mode flag in true/false\nfor switch_id+port

== Discovery process ==
TickSpout -> WatchListBolt: tick
WatchListBolt -> WatcherBolt: emit list of switch_id+port_list\nrouting by switch_id

WatcherBolt -> WatcherBolt: add switch_id+port to await response listfdsfds
WatcherBolt -> FL: sent message with switch_id+port_list
...
alt success
FL --> WatcherBolt: discovery send confirmation\nrouting by switch_id
WatcherBolt -> WatcherBolt: mark port with send confirmation
WatcherBolt -> WatcherBolt: add port to wait-for-round-trip list
    alt success
    FL --> WatcherBolt: discovery packet\nrouting by switch_id
    WatcherBolt -> WatcherBolt: remove from await list
    WatcherBolt -> DecisionMakerBolt: discovery information\nrouting by switch_id+port_id
    DecisionMakerBolt -> PortHandler

    else timeout
    ...
    TickSpout -> WatcherBolt: tick
    WatcherBolt -> WatcherBolt: find timeout ports
    WatcherBolt -> WatcherBolt: remove from await list
    WatcherBolt -> DecisionMakerBolt: discovery failed message\nrouting by switch_id+port_id
    DecisionMakerBolt -> PortHandler
    end alt

    opt have round trip support
        FL --> WatcherBolt: round trip notification
        WatcherBolt -> WatcherBolt: remove from wait-for-round-trip list
        WatcherBolt -> WatcherBolt: update round-trip-status
    end opt
else timeout
TickSpout -> WatcherBolt: tick
WatcherBolt -> WatcherBolt: find timeout ports
WatcherBolt -> WatcherBolt: remove from await list
WatcherBolt -> WatcherBolt: remove from wait-for-round-trip list
note over WatcherBolt
	FL is offline so do nothing
end note

end

== Each N time tick ==
loop all managed network endpoints
    WatcherBolt --> PortHandler: round-trip-status
end loop

@enduml
