@startuml
title Discovery Decision Maker FSM

[*] --> Init

Init -> Discovered : discovered
Init -d-> Unstable : fail

Unstable : enter / save fail time
Unstable -d-> Failed : tick, failed [time > fail-time]
Unstable -> Discovered : discovered

Failed : enter / emit fail
Failed -> Discovered : discovered

Discovered -> Unstable : fail
Discovered : enter / save failTimeLowerLimit
Discovered : enter / emit discovered
Discovered : discovered / save failTimeLowerLimit
Discovered : discovered / emit discovered

@enduml
