Internal data:
* endpoint-A
* endpoint-B
* endpoint-A-up
* endpoint-B-up

Input signals:
* isl-up
* isl-down
* isl-move

Output signals:
* bisl-up (notify BFD-port, notify reroute)
* bisl-down (notify reroute)
* bisl-bfd-enable
* bisl-bfd-disable
* isl-move

@startuml
title ISL FSM

[*] --> INIT

INIT --> DOWN : isl-up / set endpoint-(A||B)-status = UP\nisl-down / set endpoint-(A||B)-status = DOWN
INIT --> DOWN : history [history-down]
INIT --> PRE_UP : history [history-up]\n/ apply-history\n/ emit bisl-bfd-enable
INIT --> MOVED : history [history-moved]\nisl-move / set endpoint-(A||B)-status = MOVED

state upAttempt <<choice>>
state deleteAttempt <<choice>>
deleteAttempt --> DELETED : [endpoint-(A&B)-status == DOWN]

DOWN --> upAttempt : isl-up / set endpoint-(A||B)-status = DOWN && discovery-data
DOWN --> MOVED : isl-move
DOWN : enter / persist DB state
DOWN : isl-down / set endpoint-(A||B)-status = DOWN
DOWN : isl-down / persist DB state
DOWN -> deleteAttempt : isl-remove

upAttempt --> PRE_UP : [endpoint-(A&&B)-status == UP]
upAttempt --> DOWN : [else]

state preUpChoice <<choice>>

PRE_UP --> DOWN : isl-down
PRE_UP : enter / send install isl rules for source endpoint
PRE_UP : enter / send install isl rules for destination endpoint

PRE_UP --> preUpChoice : isl-rule-installed

preUpChoice --> UP : [both isl rules created]
preUpChoice --> DOWN: [isl rules installation failed]
preUpChoice --> PRE_UP: [else]


UP --> DOWN : isl-down
UP --> MOVED : isl-move
UP : enter / persist DB state
UP : enter / emit bisl-up
UP : enter [enable_bfd in DB is set] / emit bisl-bfd-enable
UP : exit / set endpoint-(A|B)-status = !UP (determine by event)
UP : exit / persist DB state
UP : exit [physical-down] / raise ISL(uni) cost
UP : exit / emit bisl-down

MOVED --> upAttempt : isl-up / set endpoint-(A|B)-status = UP
MOVED --> deleteAttempt : isl-remove
MOVED : enter / persist DB state
MOVED : enter / emit isl-move
MOVED : enter / set endpoint-(A|B)-status = MOVED
MOVED : enter / emit bisl-bfd-disable
MOVED : isl-down / set endpoint-(A|B)-status = DOWN
MOVED : isl-down / persist DB state

DELETED -> [*]
@enduml
