Internal state:
* history data (constructor)

Input signals:
* port-up
* port-down
* online
* offline

Output signals:
* physical-down
* uni-isl-setup

@startuml
title Port FSM

[*] --> INIT

INIT --> UNOPERATIONAL : offline
INIT --> OPERATIONAL : online
INIT : exit / emit uni-isl-setup

state OPERATIONAL {
    [*] --> UNKNOWN

    UNKNOWN --> DOWN : port-down
    UNKNOWN --> UP : port-up

    DOWN --> UP : port-up
    DOWN : enter / emit physical-down
    DOWN : enter / issue delWatch

    UP --> DOWN : port-down
    UP : enter / issue addWatch
}

OPERATIONAL --> UNOPERATIONAL : offline

UNOPERATIONAL --> OPERATIONAL : online
@enduml
