Internal state
* endpoint (construct time)
* remote

Input signals
* activate
* discovery
* fail
* physical-down
* bfd-up
* bfd-down
* bfd-kill

Ouput signals
* isl-move
* isl-up
* isl-down
* isl-history
* physical-down

@startuml
title UniISL FSM

[*] --> INIT
INIT --> POLL : discovery
INIT --> PAIRED : activate [have-history] / set remote, emit isl-history
INIT : fail / log error - lost ISL discovery
INIT : bfd-up / log error - lost ISL discovery
INIT : bfd-down / log error - lost ISL discovery

PAIRED -l-> POLL : discovery
PAIRED --> BFD : bfd-up
PAIRED --> DOWN : physical-down
PAIRED : fail / emit isl-down

state POLL {
    state moveChoice <<choice>>

    [*] -l-> moveChoice

    POLL_IDLE --> moveChoice : discovery
    POLL_IDLE : fail / emit isl-down

    state selfLoopChoice <<choice>>

    moveChoice --> POLL_UP : [else]
    moveChoice --> selfLoopChoice : [remote is changed] / emit isl-move

    selfLoopChoice --> POLL_UP : [else]
    selfLoopChoice -r-> POLL_IDLE : [self-loop]

    POLL_UP --> POLL_IDLE : next
    POLL_UP : enter [have speaker event] / set remote
    POLL_UP : enter [have speaker event] / emit isl-up
}
POLL --> BFD : bfd-up
POLL --> DOWN : physical-down

state BFD {
    [*] --> BFD_UP

    BFD_UP -r-> BFD_DOWN : bfd-down
    BFD_UP : enter / emit isl-up

    BFD_DOWN -l-> BFD_UP : bfd-up
    BFD_DOWN : enter / emit isl-down
}
BFD --> PAIRED : bfd-kill
BFD --> DOWN : physical-down

DOWN --> POLL : discovery
DOWN --> BFD : bfd-up
DOWN : enter / emit isl-down

@enduml
