
node {
    stage ("Pull") {
        checkout scm
    }

    stage ("Build") {
        dir("src/atdd"){
            sh 'mvn compile'
        }
    }

    stage ("Test") {
        dir("src/atdd"){
            sh 'mvn verify'
        }
    }

}
