@startuml
title Switch rules and meters validation

actor User
boundary Northbound as NB
participant SwitchManager << Hub >>
participant ValidationService
participant Floodlight as FL
database DAO

User -> NB : Switch validate

activate NB
NB -> SwitchManager : SwitchValidateRequest
activate SwitchManager

SwitchManager ->> FL : DumpRulesRequest
deactivate SwitchManager
FL -> SwitchManager : SwitchFlowEntries

SwitchManager ->> FL : DumpMetersRequest
deactivate SwitchManager
FL -> SwitchManager : SwitchMeterEntries

activate SwitchManager
SwitchManager -> ValidationService : Validate rules
activate ValidationService
ValidationService -> DAO : Get path segments\nby dst switch id
activate DAO
DAO -> ValidationService : Path segments
deactivate DAO
ValidationService -> DAO : Get paths\nby src switch id
activate DAO
DAO -> ValidationService : Flow paths
deactivate DAO
ValidationService -> ValidationService : Compute\nmissing/proper/excess\nrules

ValidationService -> SwitchManager : Validate rules\nresult
deactivate ValidationService

SwitchManager -> ValidationService : Validate meters
activate ValidationService

ValidationService -> DAO : Get paths\nby src switch id
activate DAO
DAO -> ValidationService : Flow paths
deactivate DAO
ValidationService -> ValidationService : Compute\nmissing/misconfigured\n/proper/excess\nmeters

ValidationService -> SwitchManager : Validate meters\nresult
deactivate ValidationService

SwitchManager -> NB : SwitchValidationResponse
deactivate SwitchManager
NB -> User : SwitchValidationResult
deactivate NB

@enduml
