@startuml
title Switch validate FSM

[*] --> START

START --> COLLECT_DATA : next
START --> FINISHED_WITH_ERROR : error

COLLECT_DATA --> VALIDATE : ready
COLLECT_DATA --> FINISHED_WITH_ERROR : error
COLLECT_DATA : enter / emit-requests
COLLECT_DATA : rules-received / save-response, fire ready if all responses received
COLLECT_DATA : expected-default-rules-received / save-response, fire ready if all responses received
COLLECT_DATA : groups-received / save-response, fire ready if all responses received
COLLECT_DATA : meters-received / save-response, fire ready if all responses received
COLLECT_DATA : expected-default-meters-received / save-response, fire ready if all responses received
COLLECT_DATA : meters-unsupported / save-response, fire ready if all responses received

VALIDATE --> FINISHED : next
VALIDATE --> FINISHED_WITH_ERROR : error
VALIDATE : enter / do-switch-validation

FINISHED : enter [sync-was-requested] / run-switch-sync
FINISHED : enter [!sync-was-requested] / send-validate-response

FINISHED_WITH_ERROR : enter / send-error-response

@enduml
