INSERT INTO VERSION_ENTITY (Version_ID, Version_Number, Version_Deployment_Date)
VALUES (30, 30, CURRENT_TIMESTAMP);

INSERT  INTO ACTIVITY_TYPE (activity_type_id, activity_name) VALUES 
	(43, 'UPDATE_SWITCH_LOCATION');

INSERT INTO KILDA_PERMISSION (PERMISSION_ID, PERMISSION, IS_EDITABLE, IS_ADMIN_PERMISSION, STATUS_ID, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE,DESCRIPTION) VALUES 
	(359, 'sw_switch_location_update', false, false, 1, 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP, 'Permission to update switch location');
	
INSERT INTO ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) VALUES 
	(2, 359);