INSERT INTO "VERSION" (Version_ID, Version_Number, Version_Deployment_Date)
VALUES (24, 24, CURRENT_TIMESTAMP);

INSERT  INTO "ACTIVITY_TYPE" (activity_type_id, activity_name) VALUES 
	(41, 'UPDATE_ISL_BFD_FLAG');

INSERT INTO "KILDA_PERMISSION" (PERMISSION_ID, PERMISSION, IS_EDITABLE, IS_ADMIN_PERMISSION, STATUS_ID, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE,DESCRIPTION) VALUES 
	(353, 'isl_update_bfd_flag', false, false, 1, 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP, 'Permission to update isl bfd flag');
	
INSERT INTO "ROLE_PERMISSION" (ROLE_ID,PERMISSION_ID) VALUES 
	(2, 353);