INSERT INTO "VERSION" (Version_ID, Version_Number, Version_Deployment_Date)
VALUES (22, 22, CURRENT_TIMESTAMP);

INSERT  INTO "ACTIVITY_TYPE" (activity_type_id, activity_name) VALUES 
	(40, 'DELETE_SWITCH');

INSERT INTO "KILDA_PERMISSION" (PERMISSION_ID, PERMISSION, IS_EDITABLE, IS_ADMIN_PERMISSION, STATUS_ID, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE,DESCRIPTION) VALUES 
	(351, 'sw_switch_delete', false, false, 1, 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP, 'Permission to delete switch');
	
INSERT INTO "ROLE_PERMISSION" (ROLE_ID,PERMISSION_ID) VALUES 
	(2, 351);