INSERT INTO "VERSION" (Version_ID, Version_Number, Version_Deployment_Date)
VALUES (2, 2, CURRENT_TIMESTAMP);


INSERT  INTO "ACTIVITY_TYPE" (activity_type_id, activity_name) VALUES 
	(1, 'FLOW_VALIDATE'),
	(2, 'FLOW_REROUTE'),
	(3, 'SWITCH_RULES'),
	(4, 'ISL_UPDATE_COST'),
	(5, 'DELETE_PERMISSION'),
	(6, 'CREATE_PERMISSION'),
	(7, 'UPDATE_PERMISSION'),
	(8, 'CREATE_ROLE'),
	(9, 'DELETE_ROLE'),
	(10, 'UPDATE_ROLE'),
	(11, 'ASSIGN_ROLES_TO_PERMISSION'),
	(12, 'CREATE_USER'),
	(13, 'UPDATE_USER'),
	(14, 'DELETE_USER'),
	(15, 'ASSIGN_USERS_BY_ROLE'),
	(16, 'CHANGE_PASSWORD'),
	(17, 'RESET_PASSWORD'),
	(18, 'ADMIN_RESET_PASSWORD'),
	(19, 'RESET_2FA'),
	(20, 'UPDATE_USER_SETTINGS');
	
INSERT INTO "KILDA_PERMISSION" (PERMISSION_ID, PERMISSION, IS_EDITABLE, IS_ADMIN_PERMISSION, STATUS_ID, CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE,DESCRIPTION) VALUES 
	(32, 'menu_user_activity', false, false, 1, 1, CURRENT_TIMESTAMP, 1, CURRENT_TIMESTAMP, 'Permission for user activity menu');
	
INSERT INTO "ROLE_PERMISSION" (ROLE_ID,PERMISSION_ID) VALUES 
	(2, 32);
	