---
- hosts: localhost

  tasks:

  - name: create opt dir
    file: path=/opt state=directory

  - name: get hbase
    unarchive:
      src=/src/hbase-1.2.4-bin.tar.gz
      dest=/opt
      remote_src=yes
      owner=root
      group=root

  - name: create hbase link
    file: src=/opt/hbase-1.2.4 dest=/opt/hbase state=link owner=root group=root

