@startuml
hide empty description
title Flow loop delete FSM

[*] -d-> INITIALIZED

INITIALIZED --> FLOW_VALIDATED : NEXT
INITIALIZED --> FINISHED_WITH_ERROR : TIMEOUT

FLOW_VALIDATED --> FLOW_LOOP_REMOVED : NEXT
FLOW_VALIDATED --> FLOW_STATUS_REVERTED : TIMEOUT/ERROR

FLOW_LOOP_REMOVED --> DELETING_LOOP_RULES : NEXT
FLOW_LOOP_REMOVED --> FLOW_STATUS_REVERTED : TIMEOUT/ERROR

DELETING_LOOP_RULES --> DELETING_LOOP_RULES : RESPONSE_RECEIVED/ERROR_RECEIVED
DELETING_LOOP_RULES --> LOOP_RULES_DELETED : RULES_DELETED
DELETING_LOOP_RULES --> FLOW_LOOP_REMOVED : TIMEOUT/ERROR

LOOP_RULES_DELETED --> FLOW_STATUS_UPDATED : NEXT
LOOP_RULES_DELETED --> FLOW_STATUS_REVERTED : TIMEOUT/ERROR

FLOW_STATUS_UPDATED --> FINISHED : NEXT
FLOW_STATUS_UPDATED --> FINISHED_WITH_ERROR : ERROR

FLOW_STATUS_REVERTED --> FINISHED_WITH_ERROR : NEXT/ERROR

FINISHED --> [*]
FINISHED_WITH_ERROR --> [*]
@enduml