@startuml
hide empty description
title Flow loop create FSM

[*] -d-> INITIALIZED

INITIALIZED --> FLOW_VALIDATED : NEXT
INITIALIZED --> FINISHED_WITH_ERROR : TIMEOUT

FLOW_VALIDATED --> FLOW_LOOP_CREATED : NEXT
FLOW_VALIDATED --> FLOW_STATUS_REVERTED : TIMEOUT/ERROR

FLOW_LOOP_CREATED --> INSTALLING_LOOP_RULES : NEXT
FLOW_LOOP_CREATED --> FLOW_LOOP_REMOVED : TIMEOUT/ERROR

INSTALLING_LOOP_RULES --> INSTALLING_LOOP_RULES : RESPONSE_RECEIVED/ERROR_RECEIVED
INSTALLING_LOOP_RULES --> LOOP_RULES_INSTALLED : RULES_INSTALLED
INSTALLING_LOOP_RULES --> DELETING_LOOP_RULES : TIMEOUT/ERROR

LOOP_RULES_INSTALLED --> VALIDATING_LOOP_RULES : NEXT
LOOP_RULES_INSTALLED --> DELETING_LOOP_RULES : TIMEOUT/ERROR

VALIDATING_LOOP_RULES --> VALIDATING_LOOP_RULES : RESPONSE_RECEIVED/ERROR_RECEIVED
VALIDATING_LOOP_RULES --> LOOP_RULES_VALIDATED : RULES_VALIDATED
VALIDATING_LOOP_RULES --> DELETING_LOOP_RULES : TIMEOUT/ERROR/MISSING_RULE_FOUND

LOOP_RULES_VALIDATED --> FLOW_STATUS_UPDATED : NEXT
LOOP_RULES_VALIDATED --> DELETING_LOOP_RULES : ERROR

FLOW_STATUS_UPDATED --> FINISHED : NEXT
FLOW_STATUS_UPDATED --> DELETING_LOOP_RULES : ERROR

FLOW_STATUS_REVERTED --> FINISHED_WITH_ERROR : NEXT/ERROR

FLOW_LOOP_REMOVED --> FLOW_STATUS_REVERTED : NEXT/ERROR

DELETING_LOOP_RULES --> DELETING_LOOP_RULES : RESPONSE_RECEIVED/ERROR_RECEIVED
DELETING_LOOP_RULES --> LOOP_RULES_DELETED : RULES_DELETED
DELETING_LOOP_RULES --> FLOW_LOOP_REMOVED : TIMEOUT/ERROR

LOOP_RULES_DELETED --> FLOW_LOOP_REMOVED : NEXT/ERROR

FINISHED --> [*]
FINISHED_WITH_ERROR --> [*]
@enduml