@startuml
title Switch rules and meters sync

actor User
boundary Northbound as NB
participant SwitchManager << Hub >>
participant SpeakerWorker
participant Floodlight as FL

User -> NB : Switch sync rules

activate NB
NB -> SwitchManager : SwitchValidateRequest\nperformSync=true
activate SwitchManager

SwitchManager -> SwitchManager : Switch validate

opt Missing rules exists
    SwitchManager -> SwitchManager : Rule installation commands
end

opt Excess rules exists and removeExcess=true
    SwitchManager -> SwitchManager : Rule remove commands
end

group Sending rules commands
    opt Missing rules commands exists
        loop for each missing rule
            SwitchManager ->> SpeakerWorker : BaseSpeakerCommandsRequest
            SpeakerWorker ->> FL : BaseSpeakerCommandsRequest

            FL ->> SpeakerWorker
            SpeakerWorker ->> SwitchManager
        end
    end
    opt Excess rules commands exists
        loop for each excess rule
            SwitchManager ->> SpeakerWorker : DeleteSpeakerCommandsRequest
            SpeakerWorker ->> FL : DeleteSpeakerCommandsRequest
            FL ->> SpeakerWorker
            SpeakerWorker ->> SwitchManager
        end
    end

end

opt processMeters=true, removeExcess=true and Excess meters exists
    SwitchManager -> SwitchManager : process excess meters id
end

opt Excess meters commands exists
    loop for each excess meter
        SwitchManager ->> SpeakerWorker : DeleteSpeakerCommandsRequest
        SpeakerWorker ->> FL : DeleteSpeakerCommandsRequest
        FL ->> SpeakerWorker
        SpeakerWorker --> SwitchManager
    end
end

SwitchManager -> SwitchManager: make SwitchSyncResponse
SwitchManager ->> NB: SwitchSyncResponse
deactivate SwitchManager

NB -> User: SwitchSyncResult
deactivate NB

@enduml

