@startuml
title Switch synchronization

actor User
boundary Northbound as NB
participant SwitchManager << Hub >>
participant CommandBuilder
participant Floodlight as FL
database DAO

User -> NB : Switch sync rules

activate NB
NB -> SwitchManager : SwitchValidateRequest\nperformSync=true
activate SwitchManager

SwitchManager -> SwitchManager : Switch validate

opt Missing rules exists
    SwitchManager -> CommandBuilder : buildCommandsToCreateMissingRules
    activate CommandBuilder
    CommandBuilder -> CommandBuilder : Build commands
    CommandBuilder -> SwitchManager : Rule installation commands
    deactivate CommandBuilder
end

opt Excess rules exists and removeExcess=true
    SwitchManager -> CommandBuilder : buildCommandsToRemoveExcessRules
    activate CommandBuilder
    CommandBuilder -> CommandBuilder : Build commands
    CommandBuilder -> SwitchManager : Rule remove commands
    deactivate CommandBuilder
end

opt Excess meters exists and removeExcess=true
    SwitchManager -> SwitchManager : process excess meters id
end

deactivate SwitchManager

group Sending commands
    opt Missing rules commands exists
        SwitchManager ->> FL : BatchInstallRequest
        FL ->> SwitchManager : BatchFlowInstallResponse
    end
    opt Excess rules commands exists
        SwitchManager ->> FL : BatchRemoveRequest
        FL ->> SwitchManager : BatchFlowRemoveResponse
    end
    opt Excess meters commands exists
        SwitchManager ->> FL : BatchRemoveMeters
        FL ->> SwitchManager : BatchMetersRemoveResponse
    end
end


SwitchManager -> SwitchManager: make SwitchSyncResponse
activate SwitchManager
SwitchManager ->> NB: SwitchSyncResponse
deactivate SwitchManager

NB -> User: SwitchSyncResult
deactivate NB

@enduml

